export const ko: Record<string, string> = {
    appTitle: 'BanaNyang',
    appDescription: 'AI-based Character Concept Art Generator',
    'error.title': '오류',
    'error.pasteImage': '이미지를 붙여넣는 데 실패했습니다.',
    'uploader.clickToUpload': '클릭하여 업로드',
    'uploader.orDragAndDrop': '또는 드래그 앤 드롭',
    removeImage: '이미지 제거',
    'rightPanel.title': '생성 도구',
    'tooltip.previousImage': '이전 이미지',
    'tooltip.nextImage': '다음 이미지',
    'tooltip.downloadImage': '이미지 다운로드',
    'shortcuts.general': '일반',
    'shortcuts.editing': '편집',
    'shortcuts.generation': '생성',
    'shortcuts.tools': '도구',
    'tooltip.downloadMp4': 'MP4 다운로드',
    'tooltip.downloadGif': 'GIF 다운로드',
    'tooltip.downloadAgain': '다시 다운로드',
    close: '닫기',
    'viewer.zoomHint': '클릭: 확대 | Alt+클릭: 축소 | 스페이스바+드래그: 이동',
    deselectAll: '전체 선택 해제',
    deselect: '선택 해제',
    'error.apiKeyMissing': 'API 키가 필요합니다. 사용량 플랜을 설정해주세요.',
    'error.apiKeyInvalid': 'API 키가 유효하지 않습니다. 확인 후 다시 시도해주세요.',
    'error.noOriginalImage': '생성을 시작하려면 원본 이미지를 지정하거나 프롬프트를 입력해야 합니다.',
    'error.noOptionsSelected': '생성할 내용이 없습니다. 옵션을 선택해주세요.',
    'error.modificationRequiresReference': '수정을 위해서는 참조 이미지가 필요합니다.',
    'error.cancelled': '작업이 취소되었습니다.',
    'error.permissionDenied': '파일 시스템 접근 권한이 거부되었습니다.',
    'error.fsApiNotSupported': '브라우저가 파일 시스템 API를 지원하지 않습니다.',
    'error.directorySelectFailed': '저장 폴더를 선택하는 데 실패했습니다.',
    'error.saveFailed': '파일 저장에 실패했습니다.',
    'error.translationFailed': '프롬프트 번역에 실패했습니다.',
    'error.poseAnalysisFailed': '포즈 분석에 실패했습니다.',
    'error.modelNameMissing': '모델 이름이 설정되지 않았습니다.',
    'error.quotaExceeded': '월간 무료 크레딧을 모두 사용했습니다.',
    'error.rateLimited': 'API 요청 한도에 도달했습니다. 잠시 후 다시 시도해 주세요.',
    'error.rateLimitedAutoResume': '현재 API 요청 한도를 일시적으로 초과했습니다. 시스템이 자동으로 재요청을 진행 중이니 잠시만 기다려주세요 ⏳',
    'error.loadWorkspaceFailed': '워크스페이스를 불러오는 데 실패했습니다. 파일이 손상되었을 수 있습니다.',
    'error.saveWorkspaceFailed': '워크스페이스를 저장하는 데 실패했습니다.',
    'error.vertexFailed': 'Vertex AI 호출 실패. Google AI Studio 탭으로 전환하거나 프로젝트 설정을 확인하세요.',
    'error.vertexAuthFailed': 'Vertex AI 인증 실패. 설정에서 Google 계정을 다시 연결해 주세요.',
    'error.vertexModelUnavailable': '현재 모델은 Vertex AI에서 사용할 수 없습니다. 모델을 변경하거나 Google AI Studio 탭으로 전환하세요.',
    'error.noGeminiBackend': 'Gemini 백엔드가 선택되지 않았습니다. 설정에서 Vertex AI 또는 Google AI Studio를 활성화하세요.',
    'badge.vertexAi': 'Vertex AI',
    'badge.aiStudio': 'AI Studio',
    'badge.openai': 'OpenAI',
    'badge.flux': 'Flux',
    'error.unknown': '알 수 없는 오류가 발생했습니다.',
    'error.invalidRequest': '잘못된 요청입니다. 입력값을 확인해주세요.',
    'error.noResponse': '모델로부터 응답을 받지 못했습니다.',
    'error.finishSafety': '안전 설정에 의해 콘텐츠 생성이 중단되었습니다.',
    'error.finishUnspecified': '알 수 없는 이유로 콘텐츠 생성이 중단되었습니다.',
    'error.textResponse': '모델이 이미지가 아닌 텍스트를 반환했습니다.',
    'error.noImage': '생성된 이미지가 없습니다.',
    'error.apiGeneric': 'API 호출 중 오류가 발생했습니다.',
    'error.noOriginalWithRoles': '원본 이미지 없이 다른 역할(참조, 포즈, 배경) 이미지를 사용할 수 없습니다.',
    'error.promptBlocked': '프롬프트가 안전 정책에 의해 차단되었습니다.',
    applyFullOutfit: '전체 의상 적용',
    applyTop: '상의 적용',
    applyBottom: '하의 적용',
    clearSelection: '선택 초기화',
    resetAll: 'UI 위치 초기화',
    'tooltip.resetAll': '모든 패널의 위치와 크기를 초기화합니다.',
    'section.original.title': '입력 이미지',
    'tooltip.section.original': '캐릭터의 원본 및 참조 이미지를 업로드합니다.',
    'section.original.image': '원본 이미지',
    'tooltip.uploadOriginal': '캐릭터의 기본이 되는 원본 이미지를 업로드하세요.',
    'section.original.referenceImage.title': '참조 이미지',
    'tooltip.uploadReference': '스타일, 의상, 색상 등을 참조할 이미지를 업로드하세요.',
    'section.original.referenceImage.image': '참조 이미지',
    'section.generationOptions.fov.title': '시야각(FOV)',
    'section.cameraView.title': '카메라 뷰',
    'tooltip.section.cameraView': '카메라 각도와 시야각을 조절합니다.',
    'section.cameraControl.title': '카메라 제어',
    // Camera controls
    'camera.fov': 'FOV (시야각)',
    'camera.focalLength': '초점 거리',
    'camera.lensType.fisheye': '어안렌즈',
    'camera.lensType.standard': '표준렌즈',
    'camera.lensType.telephoto': '망원렌즈',
    'camera.anglePresets': '카메라 앵글',
    'camera.lensFocusPresets': '렌즈 & 포커스',
    'camera.shotSizePresets': '샷 크기',
    // Camera Angles
    'camera.angle.eyeLevel': '아이 레벨',
    'camera.angle.highAngle': '하이 앵글',
    'camera.angle.lowAngle': '로우 앵글',
    'camera.angle.birdsEye': '버드 아이 뷰',
    'camera.angle.wormsEye': '웜 아이 뷰',
    'camera.angle.dutchAngle': '더치 앵글',
    'camera.angle.overTheShoulder': '오버 더 숄더',
    'camera.angleTooltip.eyeLevel': '눈높이. 객관적, 평범함, 안정감, 동등한 관계.',
    'camera.angleTooltip.highAngle': '위에서 아래로 내려다봄. 피사체가 작고, 약하고, 귀엽거나, 처량하게 보임.',
    'camera.angleTooltip.lowAngle': '아래에서 위로 올려다봄. 피사체가 거대하고, 위압적이고, 영웅적이고, 공포스럽게 보임.',
    'camera.angleTooltip.birdsEye': '하늘에서 수직으로 내려다봄(탑뷰). 지형 배치, 신의 시선, 기하학적 미장센.',
    'camera.angleTooltip.wormsEye': '땅바닥에 붙어서 봄. 거인 같은 스케일, 극단적인 원근감.',
    'camera.angleTooltip.dutchAngle': '카메라를 기울임(사선). 불안, 광기, 혼란, 역동적인 액션 연출.',
    'camera.angleTooltip.overTheShoulder': '상대방 어깨너머로 피사체를 봄. 대화 중인 두 사람의 관계와 거리감 표현.',
    // Lens & Focus
    'camera.lensFocus.deepFocus': '딥 포커스',
    'camera.lensFocus.shallowFocus': '셸로우 포커스',
    'camera.lensFocus.rackFocus': '랙 포커스',
    'camera.lensFocus.fisheyeLens': '어안 렌즈',
    'camera.lensFocus.telephotoLens': '망원 렌즈',
    'camera.lensFocus.wideAngleLens': '광각 렌즈',
    'camera.lensFocusTooltip.deepFocus': '앞/뒤 모든 사물에 초점이 맞음. 풍경화, 정보량이 많은 배경 원함.',
    'camera.lensFocusTooltip.shallowFocus': '피사체만 선명하고 배경은 흐림(아웃포커싱). 인물 포트레이트, 주제 강조. (f/1.8, bokeh 프롬프트)',
    'camera.lensFocusTooltip.rackFocus': '초점이 A(앞)에서 B(뒤)로 이동함. 영상 연출 시 시선 유도.',
    'camera.lensFocusTooltip.fisheyeLens': '어안 렌즈. 화면이 둥글게 왜곡됨. 개그 컷, 또는 극도로 다이내믹한 액션, CCTV 시점.',
    'camera.lensFocusTooltip.telephotoLens': '망원 렌즈. 공간이 압축되어 보임(배경이 가까워 보임). 꽉 찬 느낌, 밀도 높은 화면 구성.',
    'camera.lensFocusTooltip.wideAngleLens': '광각 렌즈. 원근감이 과장되어 보임. 광활한 풍경, 역동적인 캐릭터 손/발 강조.',
    // Shot Sizes
    'camera.shotSize.extremeLongShot': '익스트림 롱 샷',
    'camera.shotSize.longShot': '롱 샷',
    'camera.shotSize.fullShot': '풀 샷',
    'camera.shotSize.kneeShot': '니 샷',
    'camera.shotSize.waistShot': '웨이스트 샷',
    'camera.shotSize.bustShot': '바스트 샷',
    'camera.shotSize.closeUp': '클로즈업',
    'camera.shotSize.extremeCloseUp': '익스트림 클로즈업',
    'camera.shotSizeTooltip.extremeLongShot': '아주 먼 거리. 캐릭터는 점처럼 보임. 장소, 스케일, 고립감 표현.',
    'camera.shotSizeTooltip.longShot': '인물의 전신과 배경이 함께 보임. 상황 설명, 위치 관계 파악.',
    'camera.shotSizeTooltip.fullShot': '머리 끝부터 발끝까지 꽉 차게. 액션, 의상, 전체적인 자태 강조.',
    'camera.shotSizeTooltip.kneeShot': '무릎 위부터 잡음. 무용, 액션의 움직임을 보여줄 때 유용.',
    'camera.shotSizeTooltip.waistShot': '허리 위부터 잡음. 대화 장면, 일반적인 상반신 묘사. (가장 기본)',
    'camera.shotSizeTooltip.bustShot': '가슴 위부터 잡음. 인물의 표정, 감정에 집중하기 시작함.',
    'camera.shotSizeTooltip.closeUp': '얼굴(목 위)만 꽉 차게. 강렬한 감정, 중요한 대사 강조.',
    'camera.shotSizeTooltip.extremeCloseUp': '눈, 입술, 손가락 등 특정 부위만 확대. 긴장감, 미세한 디테일 강조.',
    'tooltip.viewportControl': '드래그하여 시점을 조절하세요.',
    'section.generationOptions.cameraView.title': '카메라 뷰',
    'tooltip.aPose': '체크하면 모든 뷰 생성 시 캐릭터를 A-포즈로 고정합니다.',
    aPose: 'A-포즈로 고정',
    'tooltip.uploadBackground': '캐릭터를 합성할 배경 이미지를 업로드하세요.',
    'section.backgroundImage.title': '배경 이미지',
    'section.backgroundImage.image': '배경 이미지',
    'section.conceptDesign.title': '컨셉 디자인',
    'tooltip.section.conceptDesign': '의상, 아이템, 신체 부위 등 컨셉을 디자인합니다.',
    'section.bodyPartSelection.title': '수정 부위 선택',
    'tooltip.bodyPartConcept': '참조 이미지의 스타일을 적용할 신체 부위를 선택하세요.',
    'tooltip.uploadReferenceFirst': '먼저 참조 이미지를 업로드해야 합니다.',
    'tooltip.applyFullOutfit': '참조 이미지의 전체 의상을 적용합니다.',
    'tooltip.applyTop': '참조 이미지의 상의만 적용합니다.',
    'tooltip.applyBottom': '참조 이미지의 하의만 적용합니다.',
    'tooltip.poseControl': '포즈를 직접 그리거나, 이미지를 참조하거나, 프리셋을 선택하여 제어합니다.',
    'section.poseControl.title': '포즈 제어',
    'tooltip.deselectPose': '선택한 포즈를 해제합니다.',
    'section.poseControl.image': '포즈 참조 이미지',
    'tooltip.poseOptionsDisabled': '다른 생성 옵션이 활성화되어 있어 포즈 옵션이 비활성화되었습니다.',
    'section.actionPose.title': '액션 포즈',
    'tooltip.section.clothing': '의상 컨셉을 선택합니다.',
    'section.generationOptions.modification.clothing.title': '의상',
    'tooltip.clearClothing': '선택한 모든 의상을 해제합니다.',
    'tooltip.clothingTheme': '의상 테마를 선택하세요.',
    'theme.scifi': 'SF',
    'theme.modern': '모던',
    'theme.fantasy': '판타지',
    'clothingCategory.tops': '상의',
    'clothingCategory.outerwear': '아우터',
    'clothingCategory.bottoms': '하의',
    'clothingCategory.footwear': '신발',
    'clothingCategory.gloves': '장갑',
    'clothingCategory.hats': '모자',
    'clothingCategory.bags': '가방',
    'clothingCategory.decorations': '장식',
    'clothingCategory.sets': '세트',
    'tooltip.objectTheme': '아이템 테마를 선택하세요.',
    'tooltip.objectCategory': '아이템 카테고리',
    'objectCategory.weapons': '무기',
    'objectCategory.items': '아이템',
    'objectCategory.defense': '방어구',
    'objectCategory.creatures': '크리쳐',
    'objectCategory.swords': '검',
    'objectCategory.axes': '도끼/망치',
    'objectCategory.polearms': '장병기',
    'objectCategory.ranged': '원거리',
    'objectCategory.magic': '마법무기',
    'objectCategory.shields': '방패',
    'objectCategory.armor': '갑옷',
    'objectCategory.gadgets': '가젯',
    'objectCategory.electronics': '전자기기',
    'objectCategory.everyday': '일상용품',
    'objectCategory.artifacts': '마법물품',
    'objectCategory.environment': '환경',
    'theme.ancient': '고대',
    'theme.eastern': '동양',
    'subTab.clothingConcept': '의상 컨셉',
    'subTab.itemConcept': '아이템 컨셉',
    'tooltip.subTabClothing': '의상 컨셉 디자인 탭으로 전환',
    'tooltip.subTabItem': '아이템 컨셉 디자인 탭으로 전환',
    'poseAnalysis.analyzing': '포즈 분석 중...',
    'queue.title': '생성 대기열',
    'queue.cancelAll': '전체 취소',
    'queue.processing': '처리 중...',
    'queue.cancel': '취소',
    'queue.addToQueue': '대기열에 추가',
    generateButton: '생성',
    'taskSummary.imagePose': '이미지 포즈 생성',
    'taskSummary.imageConcept': '{item} 컨셉 아트 생성',
    'role.original': '원본',
    'role.generalRef': '참조',
    'role.costumeRef': '의상 참조',
    'tooltip.role.original': '원본 이미지로 설정',
    'tooltip.role.generalRef': '일반 참조로 설정 (최대 14개)',
    'tooltip.role.costumeRef': '의상 참조로 설정',
    'tooltip.role.poseRef': '포즈 참조로 설정',
    'tooltip.role.background': '배경 이미지로 설정',
    'action.edit': '편집',
    'tooltip.editImage': '이미지 편집 (Ctrl+T)',
    'error.selectSingleImage': '이미지를 하나만 선택해주세요.',
    'error.selectImageToEdit': '편집할 이미지를 선택해주세요.',
    'error.cannotDeleteEditingImage': '편집 중인 이미지는 삭제할 수 없습니다.',
    'contextMenu.cutImage': '이미지 잘라내기',
    'menu.image.cutImage': '이미지 잘라내기',
    'contextMenu.zoomImage': '이미지 확대',
    'contextMenu.download': '이미지 다운로드',
    'contextMenu.downloadMultiple': '이미지 {count}개 다운로드',
    'contextMenu.downloadGroupImages': '그룹 이미지 저장',
    'contextMenu.downloadSelectedImages': '선택 이미지 저장',
    'contextMenu.delete': '이미지 삭제',
    'contextMenu.deleteMemo': '메모 삭제',
    'contextMenu.addMemo': '메모',
    'contextMenu.quitApp': '종료',
    'contextMenu.flipHorizontal': '이미지 반전',
    'error.costumeRefRequired': '의상 참조 이미지가 필요합니다',
    'error.poseRefRequired': '포즈 참조 이미지가 필요합니다',
    'error.bodyPartSelectionOnlyForCostumeRef': '의상 참조에서만 부위 선택이 가능합니다.',
    'info.selectCostumeRefToUse': '의상 참조 이미지를 선택해야 사용할 수 있습니다',
    'info.applyCostumeToBodyPart': '선택한 참조 이미지의 의상을 특정 부위에 적용해보세요.',
    'taskSummary.imageViews': '{count}개 뷰 생성',
    'role.badge.original': '원본',
    'role.badge.generalRef': '참조',
    'role.badge.costumeRef': '의상',
    'role.badge.poseRef': '포즈',
    'role.badge.background': '배경',
    'role.badge.inpaintMask': '마스크',
    'taskSummary.imageEdit': '이미지 수정',
    'taskSummary.imageGenerate': '이미지 생성',
    'header.manageUsagePlan': 'API 키 및 사용량 플랜 관리',
    'tooltip.header.manageUsagePlan': 'API 키를 설정하고 사용량 플랜을 관리합니다.',
    'tooltip.monthlyCreditProgressBar': '남은 크레딧 양입니다.',
    'tooltip.creditAdjustment': '사용한 크레딧 양을 수동으로 조절할 수 있습니다.',
    'tooltip.callToolbar': '툴바 불러오기',
    'creditAdjustment.usedAmount': '사용한 크레딧',
    'creditAdjustment.updateButton': '수정',
    'section.history.title': '생성기록',
    'appSettingsModal.generalTitle': '일반',
    'appSettingsModal.canvasTitle': '캔버스',
    'appSettingsModal.toolbarTitle': '툴바',
    'appSettingsModal.workspaceTitle': '워크스페이스',
    'appSettingsModal.systemTitle': '시스템',
    'settings.showCreditInLeftPanel': '좌측 패널에 크레딧 표시',
    'tooltip.unsetSaveDirectory': '자동 저장 폴더 설정을 해제합니다.',
    'tooltip.setSaveDirectory': '생성된 이미지를 자동으로 저장할 폴더를 선택합니다.',
    'tooltip.selectAllOnPage': '현재 페이지의 모든 이미지 선택/해제',
    'tooltip.downloadSelected': '선택한 {count}개 항목 다운로드',
    'tooltip.removeSelected': '선택한 {count}개 항목 삭제',
    'history.empty': '생성된 이미지가 없습니다.',
    'pagination.previous': '이전',
    'pagination.page': '{current} / {total}',
    'pagination.next': '다음',
    'pagination.first': '첫 페이지로',
    'pagination.last': '마지막 페이지로',
    'tooltip.zoomImage': '이미지 확대',
    'tooltip.resetFov': '시야각(FOV) 초기화',
    'tooltip.fovSlider': '카메라의 시야각을 조절합니다.',
    'section.lighting.title': '조명',
    'relight.copyAll': '모든 조명 복사',
    'relight.paste': '조명 붙여넣기',
    'relight.presets': '프리셋',
    'relight.lights': '조명',
    'relight.preset.category.portrait': '인물',
    'relight.preset.category.cinematic': '영화',
    'relight.preset.category.nature': '자연',
    'relight.preset.category.creative': '창작',
    'relight.preset.category.product': '상품',
    'relight.colorTemperature': '색온도',
    'relight.colorTemp.cool': '쿨',
    'relight.colorTemp.warm': '웜',
    'relight.radius': '확산',
    'relight.specularIntensity': '하이라이트',
    'relight.shadowSoftness': '그림자',
    'relight.atmosphericEffect': '대기 효과',
    'relight.atmosphericEffect.none': '없음',
    'relight.atmosphericEffect.volumetric': '볼류메트릭',
    'relight.atmosphericEffect.god_rays': '갓레이',
    'relight.atmosphericEffect.haze': '헤이즈',
    'relight.affectedArea': '적용 영역',
    'relight.affectedArea.full': '전체',
    'relight.affectedArea.foreground': '전경',
    'relight.affectedArea.background': '배경',
    'relight.type.ambient': 'Ambient',
    'relight.type.rim': 'Rim',
    'relight.type.area': 'Area',
    'relight.type.gobo': 'Gobo',
    'relight.type.practical': 'Practical',
    'tooltip.relight.ambient': '방향 없는 균일 환경광',
    'tooltip.relight.rim': '피사체 엣지를 강조하는 역광',
    'tooltip.relight.area': '소프트박스 면광원 시뮬레이션',
    'tooltip.relight.gobo': '차단 패턴으로 만드는 그림자 조명',
    'tooltip.relight.practical': '장면 내 실제 광원 (램프, 네온 등)',
    'common.copied': '복사됨',
    'common.copy': '복사',
    'common.delete': '삭제',
    'common.reset': '초기화',
    'tooltip.costumeCreativity': '의상 변형의 창의성 수준을 조절합니다.\\n1단계는 원본과 비슷하게, 5단계는 완전히 새롭게 재해석합니다.',
    'tooltip.focalLengthSlider': '카메라의 초점 거리를 조절합니다.',
    'tooltip.paletteCategory.mood': '분위기별 색상 팔레트',
    'tooltip.paletteCategory.weather': '날씨/환경별 색상 팔레트',
    'tooltip.paletteCategory.concept': '컨셉별 색상 팔레트',
    'tooltip.paletteNumColors': '추출할 색상의 개수를 선택합니다.',
    'tooltip.deletePalette': '이 팔레트를 삭제합니다.',
    'tooltip.randomPalette': '무작위 팔레트를 선택합니다.',
    'tooltip.cameraAngleSection': '카메라 앵글 프리셋을 선택합니다.',
    'tooltip.lensFocusSection': '렌즈 및 포커스 효과를 선택합니다.',
    'tooltip.shotSizeSection': '인물의 샷 크기를 선택합니다.',
    'tooltip.poseSection': '스틱맨 형태로 포즈를 직접 그려보세요.',
    'tooltip.aiEdit.removeBackground': '이미지의 배경을 제거합니다.',
    'tooltip.aiEdit.keepBackgroundOnly': '인물을 제거하고 배경만 남깁니다.',
    'tooltip.aiEdit.extractPose': '이미지에서 포즈를 추출합니다.',
    'tooltip.aiEdit.extractOutfit': '이미지에서 의상을 추출합니다.',
    'tooltip.aiEdit.autoColoring': '스케치에 오토 페인팅을 적용합니다.',
    'tooltip.aiEdit.variation': '이미지의 변형을 생성합니다.',
    'aiEdit.pbr': 'PBR 생성',
    'aiEdit.relight': '조명 생성',
    'aiEdit.prompt': '프롬프트',
    'aiEdit.promptPlaceholder': '생성하고 싶은 내용을 입력하세요 (선택사항)',
    'appSettingsModal.resetCache': '앱 초기화',
    'confirm.resetCache': '앱을 초기화하시겠습니까? 모든 설정과 캐시가 삭제되고 앱이 재시작됩니다.',
    // Synthesis Control
    'referenceDesignControl': '의상 디자인 제어',
    'tooltip.originalPreservation': '원본의 덩어리와 색상을 유지하면서 참조 이미지의 스타일/질감/디테일을 단계적으로 적용합니다.',
    'tooltip.referenceDesign': '참조 이미지의 디자인(형태/실루엣)을 적극적으로 반영하여 의상을 재설계합니다.',
    'step.original.1': '색상만 변경',
    'step.original.2': '재질 교체',
    'step.original.3': '디테일 부착',
    'step.original.4': '내부 구조 변경',
    'step.original.5': '완전 의상 교체',
    'step.reference.1': '의상 그대로 입히기',
    'step.reference.2': '재질만 변경',
    'step.reference.3': '디자인 리폼',
    'step.reference.4': '컨셉 재해석',
    'step.reference.5': '완전한 재창조',
    // Settings UI
    'leftPanelTab.settings': '설정',
    'settings.generalTitle': '일반 설정',
    'settings.autoSaveTitle': '자동 저장',
    'settings.autoSaveImageCount': '이미지 수 기준 자동 저장',
    'settings.imagesAdded': '개 이미지 추가 시 저장',
    'settings.autoSaveInterval': '시간 간격 자동 저장',
    'settings.minutesInterval': '분마다 저장',
    'settings.autoSaveInfo': '자동 저장은 백그라운드에서 실행되며, 완료 시 알림이 표시됩니다.',
    'autoSave.notification': '워크스페이스가 자동 저장되었습니다.',
    'tooltip.lightingDirection': '광원의 방향을 조절합니다.',
    'section.lighting.intensity': '강도',
    'tooltip.lightingIntensity': '조명의 세기를 조절합니다.',
    'tooltip.resetLightIntensity': '조명 강도 초기화',
    'tooltip.clearConceptSelection': '선택한 컨셉을 모두 해제합니다.',
    'tooltip.deselectAllBodyParts': '선택한 모든 신체 부위를 해제합니다.',
    'rightPanelTab.concept': '컨셉',
    'rightPanelTab.aiEdit': 'AI',
    'rightPanelTab.camera': '카메라',
    'rightPanelTab.pose': '포즈',
    'rightPanelTab.painting': '팔레트',
    'viewport.front': '정면',
    'viewport.back': '후면',
    'viewport.right': '우측',
    'viewport.left': '좌측',
    'viewport.top': '상단',
    'viewport.bottom': '하단',
    'lightingDirection.FrontLeft': '전면 좌측',
    'lightingDirection.Front': '정면',
    'lightingDirection.FrontRight': '전면 우측',
    'lightingDirection.Left': '좌측',
    'lightingDirection.Right': '우측',
    'lightingDirection.BackLeft': '후면 좌측',
    'lightingDirection.Back': '후면',
    'lightingDirection.BackRight': '후면 우측',
    'cameraAngle.Front': '정면',
    'cameraAngle.FrontLeft': '전면 좌측',
    'cameraAngle.FrontRight': '전면 우측',
    'cameraAngle.Left': '좌측',
    'cameraAngle.Right': '우측',
    'cameraAngle.Back': '후면',
    'cameraAngle.BackLeft': '후면 좌측',
    'cameraAngle.BackRight': '후면 우측',
    'cameraViewSelector.Front': '정면',
    'cameraViewSelector.Back': '뒷면',
    'cameraViewSelector.Left': '좌측',
    'cameraViewSelector.Right': '우측',
    'tooltip.edit': '이미지 편집',
    'editModal.title': '이미지 편집',
    'editModal.cancel': '취소',
    'editModal.apply': '적용',
    'editModal.generate': '생성',
    'editModal.promptPlaceholder': '수정할 내용을 입력하세요...',
    'editModal.lasso': '마스킹',
    'editModal.lassoTooltip': '마스킹 도구',
    'editModal.clearLasso': '마스크 지우기',
    'editModal.keepBackgroundOnly': '배경만 남기기',
    'editModal.keepBackgroundOnlyTooltip': 'AI를 사용하여 이미지의 주 피사체를 제거하고 배경만 남깁니다.',
    'editModal.keepBackgroundOnlyComplete': '배경 추출 완료!',
    'tooltip.actionPoseGeneral': '일반적인 액션 포즈',
    'tooltip.actionPoseAttack': '공격적인 액션 포즈',
    'tooltip.actionPoseStandingModel': '모델처럼 서 있는 포즈',
    'tooltip.selectActionPose': '액션 포즈 선택',
    downloadComplete: '다운로드가 완료되었습니다.',
    downloadCompleteMultiple: '{count}개의 파일 다운로드가 완료되었습니다.',
    'delete.success': '{count}개의 항목을 삭제했습니다.',
    'contextMenu.alignSelection': '정렬',
    'contextMenu.uploadImage': '이미지 업로드',
    'contextMenu.saveWorkspace': '워크스페이스 저장',
    'contextMenu.loadWorkspace': '워크스페이스 불러오기',
    'contextMenu.createWorkspace': '새 워크스페이스',
    'workspace.saved': '워크스페이스가 저장되었습니다.',
    'workspace.loaded': '워크스페이스를 불러왔습니다.',
    'workspace.rename.failed': '파일 이름 변경 실패: {error}',
    'drawing.brush': '브러쉬',
    'drawing.rectangle': '사각형',
    'tooltip.drawing.rectangle': '사각형 선택 도구',
    'drawing.draw': '그리기',
    'drawing.erase': '지우기',
    'drawing.clear': '전체 삭제',
    'drawing.undo': '실행 취소 (Ctrl+Z)',
    'drawing.redo': '다시 실행 (Ctrl+Shift+Z)',
    'drawing.brushSize': '브러시 크기',
    'drawing.decreaseBrush': '브러시 크기 줄이기 (X)',
    'drawing.increaseBrush': '브러시 크기 늘리기 (C)',
    'drawing.resetBrush': '브러시 크기 초기화',
    'quotaModal.title': '무료 크레딧 소진',
    'quotaModal.body': '월간 무료 크레딧을 모두 사용했습니다.\\n계속 진행하면 개인 API 키 사용량으로 요금이 청구될 수 있습니다.',
    'quotaModal.stop': '중단',
    'quotaModal.continue': '계속 진행',
    'exitConfirmModal.title': '저장되지 않은 변경사항',
    'exitConfirmModal.bodyLoad': '저장하지 않으면 현재 작업 내용을 잃게 됩니다. 저장하시겠습니까?',
    'exitConfirmModal.bodyClose': '변경사항을 저장하지 않고 종료하면 작업 내용을 잃게 됩니다. 저장하시겠습니까?',
    'exitConfirmModal.dontSave': '저장 안 함',
    'exitConfirmModal.cancel': '취소',
    'exitConfirmModal.save': '저장',
    'usagePlanModal.title': 'API 키 설정',
    'usagePlanModal.body': 'bananyang는 Google Gemini API를 사용합니다. 원활한 이용을 위해 API 키를 입력해주세요. <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noopener noreferrer" class="text-sky-400 hover:underline">여기</a>에서 API 키를 발급받을 수 있습니다.',
    'usagePlanModal.freeTier': '무료 티어 (월간 무료 크레딧 사용)',
    'usagePlanModal.paidTier': '유료 티어 (개인 API 키 사용)',
    'usagePlanModal.google': 'Google Gemini API 키',
    'usagePlanModal.placeholder': '여기에 API 키를 붙여넣으세요',
    'usagePlanModal.apiKeyExplanation': 'API 키는 브라우저에만 저장되며 외부로 전송되지 않습니다.',
    'usagePlanModal.save': '저장',
    'tooltip.generate': '생성하기',
    'tooltip.lassoEdit': '마스킹 편집',
    'section.prompt.placeholder': 'Prompt...',
    'navigator.zoomOut': '축소',
    'navigator.zoomTo100': '100%로 확대',
    'navigator.zoomIn': '확대',
    'navigator.zoomToFit': '화면에 맞추기',
    'navigator.hide': '네비게이터 숨기기',
    'navigator.show': '네비게이터 표시',
    'contextMenu.groupSelection': '그룹생성',
    'contextMenu.ungroupSelection': '그룹해제',
    'contextMenu.mergeGroups': '그룹 병합',
    'contextMenu.renameGroup': '이름변경',
    'group.defaultName': '새 그룹',
    'tooltip.goToGroup': '그룹으로 이동',
    'removeBackground.button': '배경 제거',
    'removeBackground.tooltip': 'AI를 사용하여 이미지의 배경을 제거합니다.',
    'removeBackground.loading': '배경 제거 중...',
    'removeBackground.complete': '배경 제거 완료!',
    'copy.success': '클립보드에 복사되었습니다!',
    'copy.successMultiple': '{count}개 이미지 클립보드 복사완료',
    'generation.complete': '{count}개의 이미지 생성이 완료되었습니다!',
    'contextMenu.newWorkspace': '새 워크스페이스',
    'contextMenu.saveWorkspaceAs': '워크스페이스 다른 이름으로 저장',
    'contextMenu.copySelection': '복사',
    'contextMenu.paste': '붙여넣기',
    'error.copyFailed': '클립보드 복사 실패',
    'presets.quickAccess': '프롬프트 프리셋 퀵바',
    'presets.manage': '프리셋 관리',
    'presets.modalTitle': '프롬프트 프리셋 관리',
    'presets.newFolder': '새 폴더',
    'presets.saveCurrentPrompt': '현재 프롬프트 저장',
    'presets.folderNamePlaceholder': '폴더 이름...',
    'presets.presetNamePlaceholder': '프리셋 이름...',
    'presets.deleteFolderConfirm': '이 폴더와 포함된 모든 프리셋을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
    'presets.usePreset': '사용하기',
    'presets.delete': '삭제',
    'presets.save': '저장',
    'presets.cancel': '취소',
    'presets.noFolders': '생성된 폴더가 없습니다. "새 폴더"를 클릭하여 시작하세요.',
    'presets.noPresets': '이 폴더에 저장된 프리셋이 없습니다.',
    'presets.folder': '폴더',
    'presets.untitled': '제목 없음',
    'presets.deleteConfirm': '정말로 삭제하시겠습니까?',
    'presets.rename': '이름 변경',
    'presets.promptSaved': '프롬프트가 저장되었습니다!',
    'tooltip.translatePrompt': '어떤 언어를 입력하든 영어로 번역해줍니다',
    'translation.inProgress': '번역 중...',
    'translation.success': '번역이 완료되었습니다.',
    'translation.error': '번역에 실패했습니다.',
    'presets.saveModalTitle': '프롬프트 프리셋 저장',
    'presets.presetNameLabel': '프리셋 이름',
    'presets.folderSelectLabel': '저장할 폴더',
    'presets.noPromptToSave': '저장할 프롬프트가 없습니다.',
    'presets.manageButton': '관리...',
    'presets.saveNewPreset': '현재 프롬프트 저장',
    'presets.selectFolder': '폴더 선택',
    'presets.addNewPresetTitle': '새 프리셋 추가',
    'presets.promptContentPlaceholder': '프롬프트 내용...',
    'presets.addPresetButton': '프리셋 추가',
    'presets.toggleQuickBar': '퀵바에 고정/해제',
    'presets.export': '내보내기',
    'presets.import': '불러오기',
    'presets.exportTooltip': '모든 프롬프트 프리셋을 파일로 저장합니다',
    'presets.importTooltip': '저장된 프리셋 파일을 불러옵니다',
    'presets.exportSuccess': '프리셋 내보내기 완료!',
    'presets.exportFailed': '프리셋 내보내기 실패',
    'presets.importSuccess': '프리셋 불러오기 완료!',
    'presets.importFailed': '프리셋 불러오기 실패',
    'presets.importConfirm': '기존 프리셋을 불러온 프리셋으로 교체하시겠습니까?',
    'presets.importInvalid': '올바른 프리셋 파일이 아닙니다',
    'section.originalImage.title': '원본 이미지',
    'section.originalImage.compareMode': '비교 모드',
    'section.originalImage.maskOverlay': '마스크 표시',
    'section.originalImage.maskOverlayDisabled': '마스크 없음',
    'section.originalImage.noOriginal': '원본 이미지가 설정되지 않았습니다',
    'section.originalImage.noResults': '이 원본으로 생성된 결과가 없습니다',
    'section.originalImage.sourceMissing': '원본 이미지가 보드에서 삭제되었습니다',
    'menu.view.originalImage': '원본 이미지 패널',
    'tooltip.editTotalCredit': '최대 크레딧 수정',
    'appSettingsModal.save': '저장',
    'tooltip.header.manageAppSettings': '앱 설정 관리',
    'appSettingsModal.title': '앱 설정',
    'appSettingsModal.modelTitle': '모델 선택',
    'appSettingsModal.modelDescription': '사용할 AI 모델을 선택하세요. 각 모델별로 성능과 비용이 다릅니다.',
    'appSettingsModal.model.basic.title': 'NanoBanana',
    'appSettingsModal.model.basic.desc': '표준 속도, 기본 품질',
    'appSettingsModal.model.basic.price': '$0.067 / 장 (1K)',
    'appSettingsModal.model.pro.title': 'NanoBanana Pro',
    'appSettingsModal.model.pro.desc': '고품질, 고해상도 지원',
    'appSettingsModal.model.pro.price': '$0.067~$0.151 / 장',
    'appSettingsModal.model.pro.priceDetail': '(1K: $0.067, 2K: $0.101, 4K: $0.151)',
    'tooltip.switchToBasic': 'NanoBanana (기본) 모델로 전환',
    'tooltip.switchToPro': 'NanoBanana Pro (고품질) 모델로 전환',
    'tooltip.selectModel': '모델 선택',
    'tooltip.settings': '해상도 및 비율 설정',
    'resolution.auto': '자동',
    'aspectRatio.auto': '자동',
    'appSettingsModal.apiTitle': 'API 키 설정',
    'appSettingsModal.apiBody': 'bananyang는 Google Gemini API를 사용합니다. 원활한 이용을 위해 API 키를 입력해주세요. <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noopener noreferrer" class="text-sky-400 hover:underline">여기</a>에서 API 키를 발급받을 수 있습니다.',
    'appSettingsModal.googleApiKey': 'Google Gemini API 키',
    'appSettingsModal.apiKeyPlaceholder': '여기에 API 키를 붙여넣으세요',
    'appSettingsModal.apiKeyExplanation': 'API 키는 브라우저에만 저장되며 외부로 전송되지 않습니다.',
    'appSettingsModal.creditTitle': '크레딧 설정',
    'appSettingsModal.maxCreditLabel': '월간 최대 크레딧',
    'appSettingsModal.presetTitle': '프롬프트 설정',
    'appSettingsModal.managePresetsButton': '프리셋 관리',
    'contextMenu.copyImages': '이미지 복사',
    'contextMenu.alignImages': '이미지 정렬',
    'contextMenu.alignRoleImages': '역할이미지 정렬',
    'contextMenu.aiSortImages': 'AI 자동 그룹화',
    'aiSort.analyzing': '이미지 분석 중...',
    'aiSort.grouping': '그룹화 중...',
    'aiSort.arranging': '배치 중...',
    'aiSort.complete': 'AI 정렬 완료',
    'aiSort.error': 'AI 정렬 실패',
    'aiSort.needMore': '정렬하려면 그룹화되지 않은 이미지가 2개 이상 필요합니다.',
    'aiSort.maxGroupsOption': '최대 {n}개 그룹',
    'aiSort.othersGroupName': '기타',
    'aiSort.confirmTitle': 'AI 자동 그룹화 실행',
    'aiSort.confirmBody': '그룹이 없는 이미지 {count}개를 선택한 기준으로 분류합니다.',
    'aiSort.confirmHint': 'Gemini가 이미지를 분석하므로 수십 초가 걸릴 수 있습니다. 다른 탭에서 작업을 계속할 수 있습니다.',
    'aiSort.confirmRun': '실행',
    'aiSort.confirmCancel': '취소',
    'aiSort.axis.label': '분류 기준',
    'aiSort.axis.shape': '형태',
    'aiSort.axis.concept': '컨셉',
    'aiSort.axis.color': '색상',
    'aiSort.axis.auto': '자동',
    'aiSort.axis.shape.desc': '실루엣·구도',
    'aiSort.axis.concept.desc': '주제·분위기',
    'aiSort.axis.color.desc': '색감·톤',
    'aiSort.axis.auto.desc': '다축 최적',
    'aiSort.maxGroups.label': '그룹 수',
    'aiSort.maxGroups.auto': '자동',
    'aiSort.verifyToggle': '공통점 약한 이미지는 기타로 분리',
    'aiSort.progress.verifying': '그룹 일관성 검증 중...',
    'contextMenu.editGroup': '그룹편집',
    'contextMenu.exitGroupEdit': '편집종료',
    'leftPanelTab.history': '생성 기록',
    'leftPanelTab.chat': 'Chatbot',
    'chat.placeholder': 'bananyang에게 앱 사용법, 창의적인 아이디어 등 무엇이든 물어보세요...',
    'chat.intro': '안녕하세요! bananyang AI 챗봇입니다. 저는 프롬프트 엔지니어이자 아트 디렉터로서 여러분의 창작을 도와드립니다. \n\n제가 직접 이미지를 생성할 수는 없지만, 원하시는 이미지를 만들기 위한 최적의 **프롬프트(명령어)**를 작성해 드릴 수 있습니다. \n\n"이런 분위기의 그림을 그리고 싶어", "Midjourney용 프롬프트 짜줘" 처럼 말씀해 보세요. 앱 사용법이나 웹 검색도 도와드릴게요!',
    'chat.sources': '참고 자료',
    'chat.send': '전송',
    'contextMenu.loadWorkflow': '워크플로우',
    'appSettingsModal.apiKeyDeleted': 'API 키가 삭제되었습니다.',
    'appSettingsModal.shortcutsTitle': '단축키 설정',
    'appSettingsModal.delete': '삭제',
    'appSettingsModal.resetDefaults': '기본값으로 초기화',
    'appSettingsModal.shortcutsDescription': '단축키를 클릭하여 새로운 키 조합을 등록하세요.',
    'appSettingsModal.listening': '입력 대기 중...',
    'appSettingsModal.personalTitle': '계정 설정',
    'appSettingsModal.modeApiKey': 'API 키 사용',
    'appSettingsModal.modeGoogle': 'Google 계정 (Vertex AI)',
    'appSettingsModal.apiKeyTitle': 'Google AI Studio (API Key)',
    'appSettingsModal.googleCloudTitle': 'Vertex AI Studio (OAuth)',
    'appSettingsModal.apiKeyTab': 'Google AI Studio',
    'appSettingsModal.googleAccountTab': 'Vertex AI Studio',
    'shortcut.alignSelection': '선택 항목 정렬',
    'shortcut.groupSelection': '선택 항목 그룹화/해제',
    'shortcut.saveWorkspace': '워크스페이스 저장',
    'shortcut.saveWorkspaceAs': '다른 이름으로 저장',
    'shortcut.loadWorkspace': '워크스페이스 불러오기',
    'shortcut.deleteSelection': '선택 항목 삭제',
    'shortcut.undoDrawing': '실행 취소 (이미지 편집 및 객체 삽입)',
    'shortcut.redoDrawing': '다시 실행 (이미지 편집 및 객체 삽입)',
    'shortcut.editGroup': '그룹 편집 모드 시작/종료',
    'colorPalette.title': '색상 팔레트',
    'colorPalette.numColors': '색상 수',
    'colorPalette.random': '랜덤',
    'colorPalette.create': '팔레트 만들기',
    'colorPalette.modalTitle': '나만의 팔레트 만들기',
    'colorPalette.namePlaceholder': '팔레트 이름을 입력하세요',
    'colorPalette.categoryLabel': '카테고리',
    'colorPalette.subCategoryLabel': '하위 카테고리',
    'colorPalette.colorsLabel': '색상 선택',
    'colorPalette.hexCode': '색상 코드',
    'colorPalette.pickColor': '색상 선택',
    'colorPalette.category.mood': '분위기',
    'colorPalette.category.weather': '날씨',
    'colorPalette.category.concept': '컨셉',
    'colorPalette.subCategory.warm': '따뜻한',
    'colorPalette.subCategory.cool': '차가운',
    'colorPalette.subCategory.vibrant': '생생한',
    'colorPalette.subCategory.pastel': '파스텔',
    'colorPalette.subCategory.dark': '어두운',
    'colorPalette.subCategory.monochrome': '단색',
    'colorPalette.subCategory.sunny': '맑음',
    'colorPalette.subCategory.cloudy': '흐림',
    'colorPalette.subCategory.rainy': '비',
    'colorPalette.subCategory.snowy': '눈',
    'colorPalette.subCategory.nature': '자연',
    'colorPalette.subCategory.urban': '도시',
    'colorPalette.subCategory.fantasy': '판타지',
    'colorPalette.subCategory.sciFi': 'SF',
    'colorPalette.subCategory.earthy': '어시',
    'colorPalette.subCategory.metallic': '메탈릭',
    'colorPalette.subCategory.twilight': '황혼',
    'colorPalette.subCategory.stormy': '폭풍',
    'colorPalette.subCategory.food': '음식',
    'colorPalette.subCategory.vintage': '빈티지',
    // New subcategories
    'colorPalette.subcategory.warm': '따뜻한',
    'colorPalette.subcategory.cool': '차가운',
    'colorPalette.subcategory.neutral': '중성',
    'colorPalette.subcategory.sunny': '맑음',
    'colorPalette.subcategory.rainy': '비',
    'colorPalette.subcategory.cloudy': '흐림',
    'colorPalette.subcategory.fantasy': '판타지',
    'colorPalette.subcategory.scifi': 'SF',
    'colorPalette.subcategory.vintage': '빈티지',
    // New palettes
    'colorPalette.palette.sunset': '석양',
    'colorPalette.palette.autumn': '가을',
    'colorPalette.palette.fire': '불',
    'colorPalette.palette.ocean': '바다',
    'colorPalette.palette.winter': '겨울',
    'colorPalette.palette.ice': '얼음',
    'colorPalette.palette.earth': '대지',
    'colorPalette.palette.stone': '돌',
    'colorPalette.palette.sand': '모래',
    'colorPalette.palette.brightDay': '밝은 날',
    'colorPalette.palette.goldenHour': '황금 시간',
    'colorPalette.palette.storm': '폭풍',
    'colorPalette.palette.drizzle': '이슬비',
    'colorPalette.palette.overcast': '흐린 날',
    'colorPalette.palette.misty': '안개',
    'colorPalette.palette.magic': '마법',
    'colorPalette.palette.mystical': '신비',
    'colorPalette.palette.enchanted': '마법에 걸린',
    'colorPalette.palette.neon': '네온',
    'colorPalette.palette.cyber': '사이버',
    'colorPalette.palette.hologram': '홀로그램',
    'colorPalette.palette.sepia': '세피아',
    'colorPalette.palette.retro': '레트로',
    'colorPalette.palette.classic': '클래식',
    // New subcategories
    'colorPalette.subcategory.vibrant': '선명한',
    'colorPalette.subcategory.pastel': '파스텔',
    'colorPalette.subcategory.snowy': '눈',
    'colorPalette.subcategory.nature': '자연',
    'colorPalette.subcategory.urban': '도시',
    // New palettes - Warm
    'colorPalette.palette.desert': '사막',
    'colorPalette.palette.terracotta': '테라코타',
    'colorPalette.palette.amber': '호박',
    'colorPalette.palette.coral': '산호',
    'colorPalette.palette.peach': '복숭아',
    'colorPalette.palette.rust': '녹',
    'colorPalette.palette.copper': '구리',
    // New palettes - Cool
    'colorPalette.palette.arctic': '북극',
    'colorPalette.palette.teal': '청록',
    'colorPalette.palette.aqua': '아쿼아',
    'colorPalette.palette.navy': '네이비',
    'colorPalette.palette.sapphire': '사파이어',
    'colorPalette.palette.turquoise': '터콰이즈',
    'colorPalette.palette.mint': '민트',
    // New palettes - Neutral
    'colorPalette.palette.beige': '베이지',
    'colorPalette.palette.taupe': '타우프',
    'colorPalette.palette.charcoal': '숯',
    'colorPalette.palette.slate': '슬레이트',
    'colorPalette.palette.ash': '재',
    'colorPalette.palette.cream': '크림',
    'colorPalette.palette.ivory': '아이보리',
    // New palettes - Vibrant
    'colorPalette.palette.rainbow': '무지개',
    'colorPalette.palette.tropical': '열대',
    'colorPalette.palette.candy': '사탕',
    'colorPalette.palette.neonLights': '네온 빛',
    'colorPalette.palette.electric': '전기',
    'colorPalette.palette.citrus': '감귀류',
    'colorPalette.palette.berry': '베리',
    'colorPalette.palette.jewel': '보석',
    // New palettes - Pastel
    'colorPalette.palette.spring': '봄',
    'colorPalette.palette.baby': '베이비',
    'colorPalette.palette.lavender': '라벤더',
    'colorPalette.palette.rose': '로즈',
    'colorPalette.palette.lilac': '라일락',
    'colorPalette.palette.powder': '파우더',
    // New palettes - Sunny
    'colorPalette.palette.summer': '여름',
    'colorPalette.palette.sunrise': '일출',
    'colorPalette.palette.noon': '정오',
    'colorPalette.palette.warmBreeze': '따뜻한 바람',
    // New palettes - Rainy
    'colorPalette.palette.thunder': '천둥',
    'colorPalette.palette.monsoon': '장마',
    'colorPalette.palette.wetPavement': '젖은 포장',
    'colorPalette.palette.rainForest': '우림',
    // New palettes - Cloudy
    'colorPalette.palette.fog': '안개',
    'colorPalette.palette.haze': '연무',
    'colorPalette.palette.dusk': '황혼',
    'colorPalette.palette.dawn': '새벽',
    // New palettes - Snowy
    'colorPalette.palette.freshSnow': '신선한 눈',
    'colorPalette.palette.blizzard': '눈보라',
    'colorPalette.palette.frost': '서리',
    'colorPalette.palette.iceCrystal': '얼음 결정',
    // New palettes - Fantasy
    'colorPalette.palette.dragon': '드래곤',
    'colorPalette.palette.fairy': '요정',
    'colorPalette.palette.wizard': '마법사',
    'colorPalette.palette.elf': '엘프',
    'colorPalette.palette.dwarf': '드워프',
    'colorPalette.palette.unicorn': '유니콘',
    'colorPalette.palette.phoenix': '불사조',
    // New palettes - Sci-Fi
    'colorPalette.palette.matrix': '매트릭스',
    'colorPalette.palette.laser': '레이저',
    'colorPalette.palette.plasma': '플라즈마',
    'colorPalette.palette.circuit': '회로',
    'colorPalette.palette.alien': '외계인',
    'colorPalette.palette.space': '우주',
    'colorPalette.palette.robot': '로봇',
    // New palettes - Vintage
    'colorPalette.palette.victorian': '빅토리아',
    'colorPalette.palette.artDeco': '아르데코',
    'colorPalette.palette.fifties': '50년대',
    'colorPalette.palette.sixties': '60년대',
    'colorPalette.palette.seventies': '70년대',
    'colorPalette.palette.eighties': '80년대',
    'colorPalette.palette.antique': '골동품',
    // New palettes - Nature
    'colorPalette.palette.forest': '숲',
    'colorPalette.palette.jungle': '정글',
    'colorPalette.palette.mountain': '산',
    'colorPalette.palette.river': '강',
    'colorPalette.palette.meadow': '초원',
    'colorPalette.palette.savanna': '사바나',
    'colorPalette.palette.tundra': '툰드라',
    'colorPalette.palette.volcano': '화산',
    // New palettes - Urban
    'colorPalette.palette.cityLights': '도시 빛',
    'colorPalette.palette.concrete': '콘크리트',
    'colorPalette.palette.graffiti': '그래피티',
    'colorPalette.palette.subway': '지하철',
    'colorPalette.palette.neonSigns': '네온 간판',
    'colorPalette.palette.industrial': '산업',
    'tooltip.painting': '팔레트',
    'aiEdit.extractPose': '포즈 추출',
    'aiEdit.autoColoring': '오토 페인팅',
    'aiEdit.extractOutfit': '의상 추출',
    'aiEdit.variation': '디자인 베리에이션',
    'aiEdit.insertObject': '객체 삽입',
    'aiEdit.title': 'AI 편집',
    'aiEdit.expand': '이미지 확장',
    'editModal.confirm': '확인',
    'aiEdit.removeBackgroundDescription': 'AI가 이미지의 주 피사체를 식별하고 배경을 투명하게 제거합니다. 캐릭터 시트 제작이나 합성에 유용합니다.',
    'aiEdit.keepBackgroundOnlyDescription': 'AI가 이미지 속 주 피사체를 제거한 뒤, 비워진 공간을 주변 배경의 맥락에 맞게 자연스럽게 채워 배경만 남은 이미지를 생성합니다.',
    'aiEdit.extractPoseDescription': '이미지 속 인물의 관절 위치를 분석하여 스틱맨 형태의 포즈 이미지를 생성합니다. 다른 캐릭터에 동일한 포즈를 적용할 때 사용할 수 있습니다.',
    'aiEdit.extractOutfitDescription': '캐릭터 이미지에서 신체는 제외하고 착용하고 있는 의상, 액세서리 등만 분리하여 투명 배경 이미지로 만듭니다.',
    'aiEdit.autoColoringDescription': '흑백 스케치나 라인아트에 AI가 오토 페인팅을 적용합니다. 채색 강도를 조절하여 다양한 스타일의 결과물을 얻을 수 있습니다.',
    'aiEdit.variationDescription': '원본 이미지를 기반으로 AI가 새로운 스타일의 이미지를 생성합니다. 창의성 슬라이더를 조절하여 원본과 유사한 변형부터 새로운 해석까지 탐색할 수 있습니다.',
    'aiEdit.cropExpandDescription': '영역을 이미지 바깥으로 드래그하여 AI로 장면을 확장하거나, 안쪽으로 드래그하여 이미지를 자릅니다.',
    'aiEdit.maskingDescription': 'AI가 수정할 영역을 브러시로 칠합니다. 이 영역은 프롬프트 기반 수정, 텍스처 적용 등에 사용됩니다.',
    'aiEdit.uploadObject': '객체 이미지 업로드',
    'aiEdit.insertObjectDescription': '새로운 객체 이미지를 업로드하고 프롬프트를 입력하여 장면에 자연스럽게 합성합니다.',
    'aiEdit.insertObjectPromptPlaceholder': '삽입할 객체에 대한 설명을 입력하세요...',
    'aiEdit.creativity': '창의성',
    'aiEdit.creativityLow': '원본과 유사하게',
    'aiEdit.creativityHigh': '창의적으로',
    'aiEdit.coloringIntensity': '채색 강도',
    'aiEdit.coloringIntensity1': '기본',
    'aiEdit.coloringIntensity2': '중간',
    'aiEdit.coloringIntensity3': '상세',
    'aiEdit.coloringIntensity4': '화보',
    'aiEdit.coloringIntensity5': '극사실',
    'aiEdit.coloringIntensity1Description': '러프한 컨셉 스케치',
    'aiEdit.coloringIntensity2Description': '스케치 고도화, 디테일표현추가',
    'aiEdit.coloringIntensity3Description': '미세한 디테일과 정교한 빛/그림자를 표현합니다.',
    'aiEdit.coloringIntensity4Description': '화보 사진 스타일로 렌더링합니다.',
    'aiEdit.coloringIntensity5Description': '실제 코스프레 사진처럼 극사실적으로 렌더링합니다.',
    'aiEdit.variationLevel1': '최소한의 변형',
    'aiEdit.variationLevel2': '디테일 리프레시',
    'aiEdit.variationLevel3': '요소 리디자인',
    'aiEdit.variationLevel4': '창의적 재해석',
    'aiEdit.variationLevel5': '다양한 탐험',
    'aiEdit.variationLevel1Description': '원본의 스타일, 색상, 구성을 최대한 유지하며 미세한 변형만 적용합니다.',
    'aiEdit.variationLevel2Description': '전체 형태는 유지하면서 작은 부가요소나 표면 마감을 변경합니다.',
    'aiEdit.variationLevel3Description': '핵심 아이덴티티는 유지하면서 구조선, 패턴, 악센트 요소를 변형합니다.',
    'aiEdit.variationLevel4Description': '원본을 느슨한 영감으로 사용하여 주제, 스타일, 구성을 자유롭게 재해석합니다.',
    'aiEdit.variationLevel5Description': '형태 언어와 구성 구조를 대폭 변경하여 완전히 새로운 접근을 제안합니다.',
    'aiEdit.run.removeBackground': '배경 제거 실행',
    'aiEdit.run.keepBackgroundOnly': '배경만 남기기 실행',
    'aiEdit.run.extractPose': '포즈 추출 실행',
    'aiEdit.run.autoColoring': '오토 페인팅 실행',
    'aiEdit.run.extractOutfit': '의상 추출 실행',
    'aiEdit.run.variation': '스타일 변형 실행',
    'aiEdit.run.insertObject': '객체 삽입 실행',
    'aiEdit.run.expand': '이미지 확장 실행',
    'aiEdit.run.pbr': 'PBR 맵 생성 실행',
    'aiEdit.run.relight': '조명 생성 실행',
    'aiEdit.extractPoseLoading': '포즈 추출 중...',
    'aiEdit.extractPoseComplete': '포즈 추출 완료!',
    'aiEdit.extractOutfitLoading': '의상 추출 중...',
    'aiEdit.extractOutfitComplete': '의상 추출 완료!',
    'aiEdit.autoColoringComplete': '오토 페인팅 완료!',
    'aiEdit.expandComplete': '이미지 확장 완료!',
    'aiEdit.variationComplete': '스타일 변형 생성 완료!',
    'aiEdit.insertObjectComplete': '객체 삽입 완료!',
    // Inpainting
    'aiEdit.inpainting': '인페인팅',
    'aiEdit.inpaintingDescription': '마스크로 칠한 영역만 AI가 새로 생성합니다. 배경은 그대로 유지됩니다.',
    'aiEdit.inpaintingComplete': '인페인팅 완료!',
    'aiEdit.run.inpainting': '인페인팅 실행',
    'editor.inpaint.brushSize': '브러시 크기',
    'editor.inpaint.eraser': '지우개',
    'editor.inpaint.clearMask': '마스크 초기화',
    'editor.inpaint.promptPlaceholder': '마스크 영역에 생성할 내용을 입력하세요...',
    'editor.inpaint.title': '인페인팅',
    'editor.inpaint.startMask': '마스크 그리기 시작',
    'editor.inpaint.editMask': '마스크 다시 그리기',
    'editor.inpaint.noMask': '마스크가 없습니다',
    'editor.inpaint.maskApplied': '마스크 적용됨',
    'editor.inpaint.selectImageHint': '캔버스에서 이미지 1개를 선택하세요',
    'editor.inpaint.modeIndicator': '인페인팅 모드',
    'editor.inpaint.mode.insert': '생성',
    'editor.inpaint.mode.remove': '제거',
    'editor.inpaint.workType': '작업 유형',
    'editor.inpaint.workType.clothing': '의상/직물',
    'editor.inpaint.workType.characterEdit': '캐릭터 수정',
    'editor.inpaint.workType.backgroundFill': '배경 채우기',
    'editor.inpaint.feathering': '경계 페더링',
    'editor.inpaint.contextPadding': '주변 컨텍스트',
    'editor.inpaint.toneMatch': '톤 매칭',
    'editor.inpaint.feathering.help': '마스크 가장자리를 부드럽게 흐리게 만들어 인페인팅 결과가 원본 이미지와 자연스럽게 섞이도록 합니다. 값이 높을수록 경계가 더 부드러워집니다. 경계선이 또렷하게 보일 때 값을 올리고, 디테일이 뭉개질 때는 낮추세요.',
    'editor.inpaint.contextPadding.help': '마스크 주변의 이미지를 AI에게 얼마나 함께 보여줄지 결정합니다. 값이 높을수록 주변 컨텍스트를 더 많이 참고하여 자연스러운 결과가 나오지만 처리 영역이 넓어집니다. 작은 영역 편집은 낮게, 큰 변형은 높게 설정하세요.',
    'editor.inpaint.toneMatch.help': '인페인팅 결과의 색조와 조명을 주변 영역에 자동으로 맞춥니다. 끄면 모델 출력의 원래 톤이 유지됩니다. 결과가 주변과 색감이 어긋날 때 켜세요.',
    'editor.inpaint.referenceImages': '참조 이미지',
    'editor.inpaint.addFromCanvas': '캔버스에서 추가',
    'editor.inpaint.promptGuide': '프롬프트는 아래 프롬프트 패널에서 입력하세요',
    'editor.inpaint.presets': '프리셋',
    'editor.inpaint.preset.save': '현재 설정 저장',
    'editor.inpaint.preset.delete': '삭제',
    'editor.inpaint.preset.custom': '커스텀',
    'editor.inpaint.targetImage': '편집 대상 이미지',
    'editor.inpaint.noImageSelected': '이미지가 선택되지 않았습니다',
    'error.noMaskImage': '인페인팅을 실행하려면 마스크가 필요합니다.',
    'drawing.brushColor': '브러쉬 색상',
    'drawing.memo.add': '메모 추가 (우클릭)',
    'drawing.memo.placeholder': '메모 입력...',
    'drawing.memo.textSize': '텍스트 크기',
    'drawing.memo.textColor': '텍스트 색상',
    'drawing.memo.delete': '메모 삭제',
    'drawing.save': '저장',
    'drawing.cancel': '취소',

    // Resolution & Aspect Ratio
    'resolution': '해상도',
    'aspectRatio': '비율',
    'resolution.original': '원본',
    'resolution.512': '512px',
    'resolution.1k': '1K',
    'resolution.2k': '2K',
    'resolution.3k': '3K',
    'resolution.4k': '4K',
    'aspectRatio.original': '원본',
    'aspectRatio.1:1': '1:1',
    'aspectRatio.16:9': '16:9',
    'aspectRatio.9:16': '9:16',
    'aspectRatio.4:3': '4:3',
    'aspectRatio.3:4': '3:4',

    // BodyPart Translations
    'bodyPart.Face': '얼굴',
    'bodyPart.Hair': '머리',
    'bodyPart.Body': '몸통',
    'bodyPart.Pelvis': '골반',
    'bodyPart.LeftShoulder': '왼쪽 어깨',
    'bodyPart.RightShoulder': '오른쪽 어깨',
    'bodyPart.LeftArm': '왼팔',
    'bodyPart.RightArm': '오른팔',
    'bodyPart.BothArms': '양팔',
    'bodyPart.LeftHand': '왼손',
    'bodyPart.RightHand': '오른손',
    'bodyPart.BothHands': '양손',
    'bodyPart.LeftLeg': '왼쪽 다리',
    'bodyPart.RightLeg': '오른쪽 다리',
    'bodyPart.BothLegs': '양다리',
    'bodyPart.LeftFoot': '왼발',
    'bodyPart.RightFoot': '오른발',
    'bodyPart.BothFeet': '양발',

    // ActionPose Translations
    'actionPose.General': '일반',
    'actionPose.Attack': '공격',
    'actionPose.StandingModel': '모델 서기',

    // ObjectItem Translations - NEW Fantasy Weapons (not in existing section)
    'object.FantasyWeaponGreatsword': '대검',
    'object.FantasyWeaponRapier': '레이피어',
    'object.FantasyWeaponScimitar': '시미터',
    'object.FantasyWeaponFlamberge': '플람베르주',
    'object.FantasyWeaponClaymore': '클레이모어',
    'object.FantasyWeaponMorningStar': '모닝스타',
    'object.FantasyWeaponFlail': '도리깨',
    'object.FantasyWeaponWarAxe': '전쟁 도끼',
    'object.FantasyWeaponHalberd': '할버드',
    'object.FantasyWeaponLance': '랜스',
    'object.FantasyWeaponPike': '파이크',
    'object.FantasyWeaponTrident': '삼지창',
    'object.FantasyWeaponGlaive': '글레이브',
    'object.FantasyWeaponShortbow': '단궁',
    'object.FantasyWeaponCompositeBow': '합성궁',
    'object.FantasyWeaponSling': '투석기',
    'object.FantasyWeaponThrowingKnife': '투척용 단검',
    'object.FantasyWeaponMagicOrb': '마법 오브',
    'object.FantasyWeaponRuneBlade': '룬 블레이드',
    // ObjectItem Translations - NEW Fantasy Shields/Armor (not in existing section)
    'object.FantasyDefenseBuckler': '버클러',
    'object.FantasyDefenseHeaterShield': '히터 실드',
    'object.FantasyDefensePlateArmor': '판금 갑옷',
    'object.FantasyDefenseChainmail': '사슬 갑옷',
    'object.FantasyDefenseLeatherArmor': '가죽 갑옷',
    'object.FantasyDefenseScaleArmor': '비늘 갑옷',
    'object.FantasyDefenseGreatHelm': '그레이트 헬름',
    'object.FantasyDefenseBarbuteHelm': '바르부트 투구',
    'object.FantasyItemMagicCrystal': '마법 수정',
    'object.FantasyItemRing': '마법 반지',
    'object.FantasyItemAmulet': '부적',
    'object.FantasyItemGoblet': '성배',
    // ObjectItem Translations - Ancient Era
    'object.AncientWeaponGladius': '글라디우스',
    'object.AncientWeaponKhopesh': '코페쉬',
    'object.AncientWeaponXiphos': '크시포스',
    'object.AncientWeaponPilum': '필룸',
    'object.AncientWeaponSarissa': '사리사',
    'object.AncientDefenseScutum': '스쿠툼',
    'object.AncientDefenseAspis': '아스피스',
    'object.AncientDefenseLorica': '로리카',
    'object.AncientDefenseGaleaHelm': '갈레아 투구',
    // ObjectItem Translations - Eastern
    'object.EasternWeaponKatana': '카타나',
    'object.EasternWeaponWakizashi': '와키자시',
    'object.EasternWeaponNodachi': '노다치',
    'object.EasternWeaponNaginata': '나기나타',
    'object.EasternWeaponYari': '야리',
    'object.EasternWeaponKusarigama': '쿠사리가마',
    'object.EasternWeaponShuriken': '수리검',
    'object.EasternWeaponNunchaku': '쌍절곤',
    'object.EasternWeaponBo': '봉',
    'object.EasternWeaponJian': '검(劍)',
    'object.EasternWeaponDao': '도(刀)',
    'object.EasternWeaponGuandao': '관도',
    'object.EasternDefenseSamuraiArmor': '사무라이 갑옷',
    'object.EasternDefenseKabutoHelm': '가부토 투구',
    'object.EasternDefenseChineseLamellar': '중국 찰갑',

    // Tooltip BodyPart Translations
    'tooltip.bodyPart.Face': '얼굴 전체에 스타일을 적용합니다.',
    'tooltip.bodyPart.Hair': '머리카락 전체에 스타일을 적용합니다.',
    'tooltip.bodyPart.Body': '목부터 허리까지 몸통 전체에 스타일을 적용합니다.',
    'tooltip.bodyPart.Pelvis': '골반 및 엉덩이 부위에 스타일을 적용합니다.',
    'tooltip.bodyPart.LeftShoulder': '왼쪽 어깨에 스타일을 적용합니다.',
    'tooltip.bodyPart.RightShoulder': '오른쪽 어깨에 스타일을 적용합니다.',
    'tooltip.bodyPart.LeftArm': '왼쪽 어깨부터 손목까지 팔 전체에 스타일을 적용합니다.',
    'tooltip.bodyPart.RightArm': '오른쪽 어깨부터 손목까지 팔 전체에 스타일을 적용합니다.',
    'tooltip.bodyPart.BothArms': '양팔 전체에 스타일을 적용합니다.',
    'tooltip.bodyPart.LeftHand': '왼손에 스타일을 적용합니다.',
    'tooltip.bodyPart.RightHand': '오른손에 스타일을 적용합니다.',
    'tooltip.bodyPart.BothHands': '양손에 스타일을 적용합니다.',
    'tooltip.bodyPart.LeftLeg': '왼쪽 엉덩이부터 발목까지 다리 전체에 스타일을 적용합니다.',
    'tooltip.bodyPart.RightLeg': '오른쪽 엉덩이부터 발목까지 다리 전체에 스타일을 적용합니다.',
    'tooltip.bodyPart.BothLegs': '양다리 전체에 스타일을 적용합니다.',
    'tooltip.bodyPart.LeftFoot': '왼발에 스타일을 적용합니다.',
    'tooltip.bodyPart.RightFoot': '오른발에 스타일을 적용합니다.',
    'tooltip.bodyPart.BothFeet': '양발에 스타일을 적용합니다.',

    // ClothingItem Translations
    'clothing.ModernTShirt': '모던 티셔츠',
    'clothing.ModernShirt': '모던 셔츠',
    'clothing.ModernHoodie': '모던 후드티',
    'clothing.ModernSuitJacket': '모던 정장 재킷',
    'clothing.ModernDressTop': '모던 드레스 상의',
    'clothing.ModernSlimfitJacket': '모던 슬림핏 재킷',
    'clothing.ModernJumperJacket': '모던 점퍼 재킷',
    'clothing.ModernLongJumper': '모던 롱 점퍼',
    'clothing.ModernBlazer': '모던 블레이저',
    'clothing.ModernLongCoat': '모던 롱 코트',
    'clothing.ModernHoodedJumper': '모던 후드 점퍼',
    'clothing.ModernJeans': '모던 청바지',
    'clothing.ModernSlacks': '모던 슬랙스',
    'clothing.ModernSweatpants': '모던 스웨트팬츠',
    'clothing.ModernShorts': '모던 반바지',
    'clothing.ModernSkirt': '모던 스커트',
    'clothing.ModernDressBottom': '모던 드레스 하의',
    'clothing.ModernJoggerPants': '모던 조거 팬츠',
    'clothing.ModernHipHopPants': '모던 힙합 바지',
    'clothing.ModernSkinnyJeans': '모던 스키니진',
    'clothing.ModernSlimfitPants': '모던 슬림핏 팬츠',
    'clothing.ModernSneakers': '모던 스니커즈',
    'clothing.ModernDressShoes': '모던 드레스 슈즈',
    'clothing.ModernSandals': '모던 샌들',
    'clothing.ModernBoots': '모던 부츠',
    'clothing.ModernLeatherGloves': '모던 가죽 장갑',
    'clothing.ModernSportsGloves': '모던 스포츠 장갑',
    'clothing.ModernKnitGloves': '모던 니트 장갑',
    'clothing.ModernCap': '모던 캡',
    'clothing.ModernBeanie': '모던 비니',
    'clothing.ModernFedora': '모던 페도라',
    'clothing.ModernBucketHat': '모던 버킷햇',
    'clothing.ModernHelmet': '모던 헬멧',
    'clothing.ModernMilitaryCap': '모던 군모',
    'clothing.ModernBackpack': '모던 백팩',
    'clothing.ModernSlingBag': '모던 슬링백',
    'clothing.ModernShoulderBag': '모던 숄더백',
    'clothing.ModernToteBag': '모던 토트백',
    'clothing.ModernWatch': '모던 손목시계',
    'clothing.ModernNecklace': '모던 목걸이',
    'clothing.ModernScarf': '모던 스카프',
    'clothing.ModernShoulderArmor': '모던 어깨 갑옷',
    'clothing.ModernGauntlets': '모던 건틀릿',
    'clothing.ModernCape': '모던 망토',
    'clothing.ModernCasualSet': '모던 캐주얼 세트',
    'clothing.ModernSuitSet': '모던 정장 세트',
    'clothing.ModernUniformSet': '모던 유니폼 세트',
    'clothing.ModernStreetwearSet': '모던 스트리트웨어 세트',
    'clothing.ModernBikerSet': '모던 바이커 세트',
    'clothing.ModernDetectiveSet': '모던 탐정 세트',
    'clothing.SciFiCyberneticJacket': '사이버네틱 재킷',
    'clothing.SciFiHolographicTop': '홀로그램 상의',
    'clothing.SciFiLightArmorChest': '경갑 상체',
    'clothing.SciFiBioSuitTop': '바이오슈트 상의',
    'clothing.SciFiSpaceSuitTorso': '우주복 몸통',
    'clothing.SciFiNeonTrenchcoat': '네온 트렌치코트',
    'clothing.SciFiArmoredPants': '장갑 바지',
    'clothing.SciFiEnergyLeggings': '에너지 레깅스',
    'clothing.SciFiZeroGravityTrousers': '무중력 바지',
    'clothing.SciFiCyberpunkSkirt': '사이버펑크 스커트',
    'clothing.SciFiBioSuitBottom': '바이오슈트 하의',
    'clothing.SciFiExoskeletonLegs': '외골격 다리',
    'clothing.SciFiMagneticBoots': '자기 부츠',
    'clothing.SciFiHoverBoots': '호버 부츠',
    'clothing.SciFiCyberneticGreaves': '사이버네틱 각반',
    'clothing.SciFiEnergySandals': '에너지 샌들',
    'clothing.SciFiLightweightPlatingBoots': '경량 플레이트 부츠',
    'clothing.SciFiDataGloves': '데이터 글러브',
    'clothing.SciFiPowerGauntlets': '파워 건틀릿',
    'clothing.SciFiNanoGloves': '나노 글러브',
    'clothing.SciFiRoboticHands': '로봇 손',
    'clothing.SciFiCyberneticForearms': '사이버네틱 팔뚝',
    'clothing.SciFiVisorHelmet': '바이저 헬멧',
    'clothing.SciFiNeuroLinkHeadset': '뉴로링크 헤드셋',
    'clothing.SciFiHolographicHood': '홀로그램 후드',
    'clothing.SciFiBreathingMask': '호흡 마스크',
    'clothing.SciFiCombatHelmet': '전투 헬멧',
    'clothing.SciFiDataVisor': '데이터 바이저',
    'clothing.SciFiGravityPouch': '중력 파우치',
    'clothing.SciFiTechBackpack': '테크 백팩',
    'clothing.SciFiEnergyCellHolster': '에너지 셀 홀스터',
    'clothing.SciFiUtilityBelt': '유틸리티 벨트',
    'clothing.SciFiShoulderMountedDrone': '어깨 장착 드론',
    'clothing.SciFiFloatingPauldrons': '부유 견갑',
    'clothing.SciFiEnergyShieldEmitter': '에너지 쉴드 방출기',
    'clothing.SciFiPlasmaCables': '플라즈마 케이블',
    'clothing.SciFiPilotSuitSet': '파일럿 슈트 세트',
    'clothing.SciFiCyborgEnforcerSet': '사이보그 집행자 세트',
    'clothing.SciFiExplorerSuitSet': '탐험가 슈트 세트',
    'clothing.SciFiStealthOpsSet': '스텔스 작전 세트',
    'clothing.FantasyChainmailCoif': '사슬 코이프',
    'clothing.FantasyLeatherHood': '가죽 후드',
    'clothing.FantasyCirclet': '서클릿',
    'clothing.FantasyCrown': '왕관',
    'clothing.FantasySteelHelmet': '강철 헬멧',
    'clothing.FantasyPlateArmorChest': '판금 갑옷 상체',
    'clothing.FantasyLeatherJerkin': '가죽 저킨',
    'clothing.FantasyMageRobesTop': '마법사 로브 상의',
    'clothing.FantasyChainmailShirt': '사슬 셔츠',
    'clothing.FantasyTunic': '튜닉',
    'clothing.FantasyElvenRobe': '엘프 로브',
    'clothing.FantasyDwarvenArmor': '드워프 갑옷',
    'clothing.FantasyPlatePauldrons': '판금 견갑',
    'clothing.FantasyLeatherShoulderPads': '가죽 어깨 보호대',
    'clothing.FantasyMagePauldrons': '마법사 견갑',
    'clothing.FantasyFurMantle': '모피 망토',
    'clothing.FantasyPlateGauntlets': '판금 건틀릿',
    'clothing.FantasyLeatherBracers': '가죽 팔 보호대',
    'clothing.FantasyMageGloves': '마법사 장갑',
    'clothing.FantasyPlateGreaves': '판금 각반',
    'clothing.FantasyLeatherPants': '가죽 바지',
    'clothing.FantasyMageRobesBottom': '마법사 로브 하의',
    'clothing.FantasyChainmailLeggings': '사슬 레깅스',
    'clothing.FantasyTrousers': '바지',
    'clothing.FantasyKilt': '킬트',
    'clothing.FantasyPlateSabatons': '판금 발 보호대',
    'clothing.FantasyLeatherBoots': '가죽 부츠',
    'clothing.FantasyMageSandals': '마법사 샌들',
    'clothing.FantasyElvenBoots': '엘프 부츠',
    'clothing.FantasyTravelersCloak': '여행자 망토',
    'clothing.FantasyRoyalCape': '왕실 망토',
    'clothing.FantasyAdventurerBelt': '모험가 벨트',
    'clothing.FantasyPotionBelt': '포션 벨트',
    'clothing.FantasyKnightSet': '기사 세트',
    'clothing.FantasyRogueSet': '도적 세트',
    'clothing.FantasyWizardSet': '마법사 세트',
    'clothing.FantasyRangerSet': '레인저 세트',
    'clothing.FantasyKingSet': '왕 세트',
    // ObjectItem Translations
    'object.ModernWeaponPistol': '모던 권총',
    'object.ModernWeaponRifle': '모던 소총',
    'object.ModernWeaponShotgun': '모던 샷건',
    'object.ModernWeaponKnife': '모던 나이프',
    'object.ModernWeaponBaseballBat': '모던 야구방망이',
    'object.ModernWeaponSubmachineGun': '모던 기관단총',
    'object.ModernWeaponSniperRifle': '모던 저격소총',
    'object.ModernWeaponRevolver': '모던 리볼버',
    'object.ModernWeaponCombatKnife': '모던 전투 단검',
    'object.ModernWeaponKatana': '모던 카타나',
    'object.ModernWeaponSaber': '모던 세이버',
    'object.ModernWeaponLongsword': '모던 롱소드',
    'object.ModernWeaponMachete': '모던 마체테',
    'object.ModernItemSmartphone': '모던 스마트폰',
    'object.ModernItemLaptop': '모던 노트북',
    'object.ModernItemHeadphones': '모던 헤드폰',
    'object.ModernItemEnergyDrink': '모던 에너지 드링크',
    'object.ModernItemMedkit': '모던 구급상자',
    'object.ModernItemDrone': '모던 드론',
    'object.ModernItemCoffeeMug': '모던 커피 머그',
    'object.ModernItemBriefcase': '모던 서류가방',
    'object.ModernItemLighter': '모던 라이터',
    'object.ModernDefenseKevlarVest': '모던 케블라 조끼',
    'object.ModernDefenseBallisticShield': '모던 방탄 방패',
    'object.ModernDefenseRiotShield': '모던 진압 방패',
    'object.ModernDefenseTacticalHelmet': '모던 전술 헬멧',
    'object.SciFiWeaponPlasmaRifle': '플라즈마 소총',
    'object.SciFiWeaponLaserPistol': '레이저 권총',
    'object.SciFiWeaponEnergySword': '에너지 소드',
    'object.SciFiWeaponRailgun': '레일건',
    'object.SciFiWeaponPulseCannon': '펄스 캐논',
    'object.SciFiWeaponGaussRifle': '가우스 소총',
    'object.SciFiWeaponSonicPistol': '소닉 권총',
    'object.SciFiWeaponLaserKatana': '레이저 카타나',
    'object.SciFiWeaponEMPGrenade': 'EMP 수류탄',
    'object.SciFiWeaponSmartGrenade': '스마트 수류탄',
    'object.SciFiWeaponHeavyPlasmaCannon': '헤비 플라즈마 캐논',
    'object.SciFiWeaponCryoGun': '크라이오 건',
    'object.SciFiWeaponParticleBeamRifle': '입자빔 소총',
    'object.SciFiItemMedibot': '메디봇',
    'object.SciFiItemHolographicProjector': '홀로그램 프로젝터',
    'object.SciFiItemAntiGravityDevice': '반중력 장치',
    'object.SciFiItemPersonalDrone': '개인 드론',
    'object.SciFiItemDataPad': '데이터 패드',
    'object.SciFiDefenseEnergyShield': '에너지 쉴드',
    'object.SciFiDefenseLightCompositeArmor': '경량 복합 갑옷',
    'object.SciFiDefenseExoFrame': '엑소 프레임',
    'object.SciFiDefenseStealthCloak': '스텔스 망토',
    'object.SciFiRobotAndroid': '안드로이드',
    'object.SciFiRobotSecurityDrone': '보안 드론',
    'object.SciFiRobotAssaultMech': '강습 메카',
    'object.SciFiRobotUtilityBot': '유틸리티 봇',
    'object.SciFiRobotCyberneticAnimal': '사이버네틱 동물',
    'object.FantasyWeaponLongsword': '롱소드',
    'object.FantasyWeaponBroadsword': '브로드소드',
    'object.FantasyWeaponDagger': '단검',
    'object.FantasyWeaponBattleAxe': '배틀 액스',
    'object.FantasyWeaponWarhammer': '워해머',
    'object.FantasyWeaponMace': '메이스',
    'object.FantasyWeaponSpear': '창',
    'object.FantasyWeaponLongbow': '장궁',
    'object.FantasyWeaponCrossbow': '석궁',
    'object.FantasyWeaponMagicStaff': '마법 지팡이',
    'object.FantasyWeaponMagicWand': '마법 완드',
    'object.FantasyDefenseKiteShield': '카이트 쉴드',
    'object.FantasyDefenseRoundShield': '라운드 쉴드',
    'object.FantasyDefenseTowerShield': '타워 쉴드',
    'object.FantasyItemHealthPotion': '체력 포션',
    'object.FantasyItemManaPotion': '마나 포션',
    'object.FantasyItemSpellbook': '마법서',
    'object.FantasyItemAncientScroll': '고대 스크롤',
    'object.FantasyItemTreasureChest': '보물 상자',
    'object.FantasyItemTorch': '횃불',
    'object.FantasyCreatureDragon': '드래곤',
    'object.FantasyCreatureGoblin': '고블린',
    'object.FantasyCreatureOrc': '오크',
    'object.FantasyCreatureGriffin': '그리핀',
    'object.FantasyCreatureUnicorn': '유니콘',

    // New Modern Items
    'object.ModernWeaponTaser': '테이저건',
    'object.ModernWeaponPepperSpray': '페퍼 스프레이',
    'object.ModernWeaponCrossbow': '크로스보우',
    'object.ModernWeaponBoxingGloves': '복싱 글러브',
    'object.ModernWeaponBrassKnuckles': '너클',
    'object.ModernWeaponBaton': '삼단봉',
    'object.ModernItemWalkieTalkie': '무전기',
    'object.ModernItemFlashlight': '손전등',
    'object.ModernItemHandcuffs': '수갑',
    'object.ModernItemBinoculars': '망원경',
    'object.ModernItemCamera': '카메라',
    'object.ModernItemTablet': '태블릿',
    'object.ModernDefenseGasMask': '방독면',
    'object.ModernDefenseTacticalVest': '전술 조끼',
    'object.ModernDefenseBulletproofSunglasses': '방탄 선글라스',
    'object.ModernDefenseKneePads': '무릎 보호대',
    'object.ModernDefenseElbowPads': '팔꿈치 보호대',

    // New Sci-Fi Items
    'object.SciFiWeaponGravityGun': '중력건',
    'object.SciFiWeaponTeslaCannon': '테슬라 캐논',
    'object.SciFiWeaponPlasmaBlade': '플라즈마 블레이드',
    'object.SciFiWeaponPhaseRifle': '위상 소총',
    'object.SciFiWeaponNanoSwarmGrenade': '나노 스웜 수류탄',
    'object.SciFiItemTeleporter': '텔레포터',
    'object.SciFiItemScanner': '스캐너',
    'object.SciFiItemNanoMedInjector': '나노 치료 주사기',
    'object.SciFiItemGravBoots': '중력 부츠',
    'object.SciFiDefenseNanoShield': '나노 실드',
    'object.SciFiDefenseForceFieldGenerator': '역장 생성기',
    'object.SciFiDefenseHoloDecoy': '홀로그램 미끼',

    // Palette Names
    'colorPalette.palette.sunsetGlow': '노을빛',
    'colorPalette.palette.autumnFire': '가을 불꽃',
    'colorPalette.palette.cozyEvening': '아늑한 저녁',
    'colorPalette.palette.spicyTerracotta': '스파이시 테라코타',
    'colorPalette.palette.goldenSands': '황금빛 모래',
    'colorPalette.palette.desertSunset': '사막의 일몰',
    'colorPalette.palette.oceanBreeze': '바닷바람',
    'colorPalette.palette.mistyForest': '안개 낀 숲',
    'colorPalette.palette.winterNight': '겨울밤',
    'colorPalette.palette.glacialIce': '빙하 얼음',
    'colorPalette.palette.deepSea': '깊은 바다',
    'colorPalette.palette.lavenderFields': '라벤더 들판',
    'colorPalette.palette.neonCity': '네온 시티',
    'colorPalette.palette.tropicalPunch': '트로피컬 펀치',
    'colorPalette.palette.electricDreams': '일렉트릭 드림',
    'colorPalette.palette.synthwaveSunset': '신스웨이브 선셋',
    'colorPalette.palette.carnivalCelebration': '카니발 축제',
    'colorPalette.palette.popArt': '팝 아트',
    'colorPalette.palette.candyFloss': '솜사탕',
    'colorPalette.palette.mintSorbet': '민트 소르베',
    'colorPalette.palette.dreamyPeach': '꿈꾸는 복숭아',
    'colorPalette.palette.babyShower': '베이비 샤워',
    'colorPalette.palette.springBlossoms': '봄꽃',
    'colorPalette.palette.easterEggs': '이스터 에그',
    'colorPalette.palette.royalVelvet': '로얄 벨벳',
    'colorPalette.palette.deepSpace': '깊은 우주',
    'colorPalette.palette.midnightOil': '미드나잇 오일',
    'colorPalette.palette.gothicRomance': '고딕 로맨스',
    'colorPalette.palette.enchantedNight': '마법에 걸린 밤',
    'colorPalette.palette.noirDetective': '누아르 탐정',
    'colorPalette.palette.grayscale': '그레이스케일',

    'colorPalette.palette.blueTones': '블루 톤',
    'colorPalette.palette.charcoalSketch': '목탄 스케치',
    'colorPalette.palette.vintagePhoto': '빈티지 사진',
    'colorPalette.palette.inkWash': '수묵화',
    'colorPalette.palette.terracottaPots': '테라코타 화분',
    'colorPalette.palette.mossyStones': '이끼 낀 돌',
    'colorPalette.palette.clayPottery': '점토 도자기',
    'colorPalette.palette.redRockCanyon': '붉은 바위 협곡',
    'colorPalette.palette.goldAndSilver': '금과 은',
    'colorPalette.palette.bronzeAge': '청동 시대',
    'colorPalette.palette.polishedSteel': '광택 강철',
    'colorPalette.palette.copperPatina': '구리 녹',

    'colorPalette.palette.summerSky': '여름 하늘',
    'colorPalette.palette.fadedSunlight': '바랜 햇빛',
    'colorPalette.palette.hazyAfternoon': '흐린 오후',
    'colorPalette.palette.morningDew': '아침 이슬',
    'colorPalette.palette.beachDay': '해변의 하루',

    'colorPalette.palette.stormyGray': '폭풍우 회색',
    'colorPalette.palette.softNimbus': '부드러운 구름',
    'colorPalette.palette.drearySky': '음산한 하늘',
    'colorPalette.palette.silverLining': '희망의 빛',
    'colorPalette.palette.gloomyDay': '우울한 날',
    'colorPalette.palette.afterTheRain': '비 온 뒤',
    'colorPalette.palette.petrichor': '비 냄새',
    'colorPalette.palette.wetAsphalt': '젖은 아스팔트',
    'colorPalette.palette.foggyMorning': '안개 낀 아침',

    'colorPalette.palette.icyBlue': '얼음빛 파랑',
    'colorPalette.palette.winterGloom': '겨울 우울',
    'colorPalette.palette.meltingSnow': '녹는 눈',

    'colorPalette.palette.firstSnowfall': '첫눈',

    'colorPalette.palette.blueHour': '블루 아워',
    'colorPalette.palette.civilTwilight': '시민 박명',
    'colorPalette.palette.thunderstorm': '뇌우',
    'colorPalette.palette.hurricane': '허리케인',
    'colorPalette.palette.tornadoAlley': '토네이도 앨리',
    'colorPalette.palette.dustStorm': '모래폭풍',
    'colorPalette.palette.forestFloor': '숲 바닥',
    'colorPalette.palette.desertSands': '사막 모래',
    'colorPalette.palette.driedHerbs': '마른 허브',
    'colorPalette.palette.winterForest': '겨울 숲',
    'colorPalette.palette.volcanicLava': '화산 용암',
    'colorPalette.palette.coralReef': '산호초',
    'colorPalette.palette.jungleCanopy': '정글 캐노피',
    'colorPalette.palette.cityAtNight': '밤의 도시',
    'colorPalette.palette.concreteJungle': '콘크리트 정글',
    'colorPalette.palette.urbanDecay': '도시의 쇠퇴',
    'colorPalette.palette.industrialHaze': '산업 안개',
    'colorPalette.palette.graffitiAlley': '그래피티 골목',
    'colorPalette.palette.skyscraperGlass': '마천루 유리',
    'colorPalette.palette.subwayStation': '지하철역',
    'colorPalette.palette.enchantedForest': '마법의 숲',
    'colorPalette.palette.dragonsHoard': '용의 보물',
    'colorPalette.palette.ancientRuins': '고대 유적',
    'colorPalette.palette.fadedParchment': '바랜 양피지',
    'colorPalette.palette.fairyWings': '요정의 날개',
    'colorPalette.palette.dwarvenForge': '드워프 대장간',
    'colorPalette.palette.elvenForest': '엘프 숲',
    'colorPalette.palette.cyberpunk': '사이버펑크',
    'colorPalette.palette.starshipHull': '우주선 선체',
    'colorPalette.palette.dystopianSteel': '디스토피아 강철',
    'colorPalette.palette.derelictSpaceship': '버려진 우주선',
    'colorPalette.palette.alienPlanet': '외계 행성',
    'colorPalette.palette.hologramBlue': '홀로그램 블루',
    'colorPalette.palette.spaceshipInterior': '우주선 내부',
    'colorPalette.palette.berryPie': '베리 파이',
    'colorPalette.palette.citrusSplash': '시트러스 스플래시',
    'colorPalette.palette.coffeeHouse': '커피 하우스',
    'colorPalette.palette.iceCreamShop': '아이스크림 가게',
    'colorPalette.palette.sixtiesPsychedelic': '60년대 사이키델릭',
    'colorPalette.palette.seventiesEarthTones': '70년대 어스 톤',
    'colorPalette.palette.eightiesNeon': '80년대 네온',

    'colorPalette.heroEmpty': '팔레트를 선택하세요',
    'colorPalette.selectedPalette': '선택된 팔레트',
    'colorPalette.addPalette': '팔레트 추가',
    'colorPalette.expandAll': '펼치기',
    'colorPalette.collapseAll': '접기',

    'tooltip.modelSelector': '모델 선택',

    // Relighting feature
    'editModal.relight': '조명 조절',
    'relight.title': '조명 스튜디오',
    'relight.addLight': '조명 추가',
    'relight.lightType': '조명 타입',
    'relight.lightColor': '조명 색상',
    'relight.lightIntensity': '조명 강도',
    'relight.lightDirection': '조명 방향',
    'relight.deleteLight': '조명 삭제',
    'relight.noLights': '조명이 없습니다. "조명 추가" 버튼을 클릭하세요.',
    'relight.type.omni': 'Omni',
    'relight.type.direct': 'Direct',
    'relight.type.sun': 'Sun',
    'tooltip.relight.omni': '모든 방향으로 빛을 발산하는 조명',
    'tooltip.relight.direct': '특정 방향으로만 빛을 발산하는 조명',
    'tooltip.relight.sun': '태양과 같은 평행광 조명',
    'relight.generateComplete': '조명 조절 완료!',
    // Menu bar
    'menu.file': '파일',
    'menu.file.uploadImage': '이미지 업로드',
    'menu.file.saveWorkspace': '저장',
    'menu.file.saveWorkspaceAs': '다른이름저장',
    'menu.file.loadWorkspace': '새 탭으로 불러오기',
    'menu.file.loadWorkspaceInCurrentTab': '현재 탭에 불러오기',
    'menu.file.promptPresets': '프롬프트 프리셋',
    'menu.file.workspaceGroup': '워크스페이스',
    'menu.file.newWorkspace': '새로 만들기',
    'menu.file.exit': '종료',
    'menu.edit': '편집',
    'menu.edit.copy': '복사',
    'menu.edit.paste': '붙여넣기',
    'menu.edit.delete': '삭제',
    'menu.edit.alignImages': '이미지 정렬',
    'menu.edit.aiSortImages': 'AI 자동 그룹화',
    'menu.edit.group': '그룹',
    'menu.edit.group.create': '생성',
    'menu.edit.group.ungroup': '해제',
    'menu.edit.group.rename': '이름변경',
    'menu.edit.group.edit': '편집',
    'menu.edit.settings': '설정',
    'menu.image': '이미지',
    'menu.image.zoom': '이미지 확대',
    'menu.image.edit': '이미지 편집',
    'menu.image.editGroup': '이미지 편집',
    'menu.image.crop': '자르기/확장',
    'menu.image.object': '객체 삽입',
    'menu.image.relight': '조명 설정',
    'menu.image.pbr': 'PBR 맵',
    'menu.image.flipHorizontal': '이미지 반전',
    'menu.image.download': '이미지 다운로드',
    'menu.image.aiEdit': 'AI편집',
    'menu.image.aiEdit.autoColoring': '페인팅',
    'menu.image.aiEdit.variation': '바리에이션',
    'menu.image.aiEdit.extractPose': '포즈추출',
    'menu.image.aiEdit.extractOutfit': '의상추출',
    'menu.image.aiEdit.removeBackground': '배경제거',
    'menu.image.aiEdit.keepBackground': '배경유지',
    'menu.image.aiEdit.insertObject': '삽입',
    'menu.image.aiEdit.expand': '확장',
    'menu.image.aiEdit.inpainting': '인페인팅',
    'menu.image.aiEdit.pbr': 'PBR',
    'menu.image.aiEdit.relight': '조명',
    'menu.image.role': '역할',
    'menu.image.role.original': '원본',
    'menu.image.role.generalRef': '참조',
    'menu.image.role.costumeRef': '의상',
    'menu.image.role.poseRef': '포즈',
    'menu.image.role.background': '배경',
    'menu.image.addMemo': '메모',
    'menu.image.loadWorkflow': '워크플로우',
    'menu.edit.imageTools': '이미지 도구',
    'menu.edit.imageTools.basic': '기본',
    'menu.edit.imageTools.edit': '편집',
    'menu.edit.imageTools.aiEdit': 'AI 편집',
    'menu.edit.imageTools.role': '역할',
    'menu.edit.imageTools.other': '기타',
    'menu.view': '보기',
    'menu.view.rightPanel': '패널',
    'menu.view.rightPanel.concept': '컨셉',
    'menu.view.rightPanel.camera': '카메라',
    'menu.view.rightPanel.pose': '포즈',
    'menu.view.rightPanel.painting': '페인팅',
    'menu.view.rightPanel.aiEdit': 'AI편집',
    'menu.view.glassEffect': '글래스',
    'menu.view.resetUI': 'UI초기화',
    'menu.view.refreshVRAM': 'VRAM',
    'menu.view.alwaysOnTop': '항상 위',
    'menu.view.history': '생성기록',
    'menu.view.tools': '생성 도구',
    'menu.help': '도움말',
    'menu.help.shortcuts': '단축키',
    'menu.help.settings': '설정',
    'menu.help.resetApp': '초기화',
    'menu.help.resetAppConfirm': '정말로 앱을 초기화하시겠습니까? 모든 데이터가 삭제됩니다.',
    'menu.help.about': 'BanaNyang v1.0.0',
    // Window controls
    'window.canvasImages': '캔버스 이미지',
    'window.minimize': '최소화',
    'window.maximize': '최대화',
    'window.restore': '복원',
    'window.close': '닫기',
    // Toolbar orientation
    'toolbar.layout': '툴바 레이아웃',
    'toolbar.vertical': '세로',
    'toolbar.horizontal': '가로',
    'toolbar.bindingDirection': '연결 방향',
    'toolbar.bindLeft': '왼쪽',
    'toolbar.bindRight': '오른쪽',
    'toolbar.autoConnect': '자동 연결',

    // === NEW KEYS for ternary conversions ===

    // Language settings
    'settings.language': '언어',
    'settings.languageDescription': '앱에서 사용할 언어를 선택합니다.',
    // Auto-download
    'autoDownload.title': '생성 기록 자동 다운로드',
    'autoDownload.description': '생성된 이미지를 선택한 폴더에 자동으로 저장합니다.',
    'autoDownload.folderSet': '자동 다운로드 폴더가 설정되었습니다.',
    'autoDownload.folderSetError': '폴더 선택에 실패했습니다.',
    'autoDownload.browserNotSupported': '브라우저에서는 폴더 열기가 지원되지 않습니다.',
    'autoDownload.selectFolderFirst': '먼저 저장 폴더를 선택해주세요.',
    'autoDownload.openFolder': '폴더 열기',
    'autoDownload.clearPath': '경로 해제',
    'autoDownload.noFolder': '폴더가 설정되지 않았습니다',
    'autoDownload.selectFolder': '폴더 선택',
    // Settings UI
    'settings.showCreditInLeftPanelDescription': '끄면 좌측 패널에서 크레딧 정보가 숨겨지고 생성 기록만 표시됩니다.',
    'settings.viewModelPricing': '모델별 이미지 생성 가격 보기',
    'settings.creditSettingsTitle': '월간 크레딧 설정',
    'settings.pricingPopoverTitle': '모델별 가격',
    // Session Recovery
    'sessionRecovery.title': '이전 작업 복구',
    'sessionRecovery.description': '이전에 저장되지 않은 작업 세션이 발견되었습니다. 복구하시겠습니까?',
    'sessionRecovery.noSessions': '복구 가능한 세션이 없습니다.',
    'sessionRecovery.session': '세션',
    'sessionRecovery.imageCount': '{count}개 이미지',
    'sessionRecovery.deleting': '삭제 중...',
    'sessionRecovery.delete': '🗑️ 삭제',
    'sessionRecovery.recovering': '복구 중...',
    'sessionRecovery.recover': '📂 복구',
    'sessionRecovery.tip': '💡 Tip: 작업 중 자동 저장을 활성화하면 데이터 손실을 방지할 수 있습니다.',
    'sessionRecovery.deleteAll': '모두 삭제',
    'sessionRecovery.later': '나중에',
    'sessionRecovery.deleteAllConfirm': '모든 복구 세션을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
    'sessionRecovery.deleteConfirm': '이 세션을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
    'sessionRecovery.imagesRecovered': '{count}개 이미지 복구됨',
    'sessionRecovery.recoveryFailed': '복구 실패',
    // Generation summary
    'summary.creativity': '창의성',
    'summary.step': '단계',
    'summary.intensity': '강도',
    'summary.maps': '맵',
    'summary.camera3d': '3D 카메라',
    'summary.camera': '카메라',
    'summary.shot': '샷',
    'summary.detailAttach': '디테일 부착',
    'summary.referenceControl': '참조 디자인 제어',
    'summary.light': '조명',
    'summary.object': '오브젝트',
    'summary.defaultGeneration': '기본 생성',
    // Notifications
    'notification.downloadFailed': '다운로드에 실패했습니다.',
    'notification.imageAddedToEditor': '이미지가 에디터에 추가되었습니다.',
    'notification.referenceImageAdded': '참조 이미지가 추가되었습니다.',
    // Right panel
    'rightPanel.poseDrawing': '포즈 그리기',
    'rightPanel.onlyWithOriginal': '원본 이미지가 있을 때만 사용 가능합니다',
    'rightPanel.onlyWithoutPoseRef': '포즈 참조 이미지가 없을 때만 사용 가능합니다',
    'rightPanel.cannotWithCamera': '카메라 옵션과 동시에 사용할 수 없습니다',
    'rightPanel.cannotWithPoseDrawing': '포즈 그리기와 동시에 사용할 수 없습니다',
    // Context menu
    'contextMenu.editImage': '이미지 편집',
    // Editor
    'editor.pbrMapGeneration': 'PBR 맵 생성',
    // PBR tab
    'pbr.mapLabel': '{name}',
    'pbr.multiViewTitle': 'Multi-View PBR 생성',
    'pbr.multiViewDescription': '캐릭터의 앞/뒤/좌/우 뷰에서 PBR 맵을 동시에 생성합니다. 원본 이미지가 있어야 합니다.',
    'pbr.selectMapTypes': '생성할 맵 선택',
    'pbr.toggleAll': '전체 선택/해제',
    'pbr.noMapSelected': '생성할 맵 종류를 선택해주세요.',
    'pbr.needOneImage': '최소 하나의 이미지가 필요합니다.',
    // Object tab
    'objectTab.canvasSelectTooltip': '캔버스에서 이미지를 클릭하여 객체로 삽입합니다',
    'objectTab.modeActivated': '객체삽입 모드가 활성화되었습니다. 캔버스에서 이미지를 클릭하세요.',
    'objectTab.modeDeactivated': '객체삽입 모드가 해제되었습니다.',
    'objectTab.exitMode': '객체삽입 모드 해제',
    'objectTab.enterMode': '객체삽입 모드',
    'objectTab.modeLabel': '모드',
    'objectTab.editMode': '편집모드',
    'objectTab.drawMode': '인페인팅',
    'objectTab.undoRedoTitle': '실행 취소/다시 실행',
    'objectTab.undoButton': '실행 취소',
    'objectTab.undoTooltip': '실행 취소 (Ctrl+Z)',
    'objectTab.redoButton': '다시 실행',
    'objectTab.redoTooltip': '다시 실행 (Ctrl+Shift+Z)',
    'objectTab.drawingTools': '그리기 도구',
    // Inpaint tab
    'inpaint.reference': '인페인팅 참조',
    'inpaint.referenceIndex': '참조 {index}',
    'inpaint.canvasSelectTooltip': '캔버스에서 이미지를 클릭하여 참조 이미지로 추가합니다',
    'inpaint.modeActivated': '참조선택 모드가 활성화되었습니다. 캔버스에서 이미지를 클릭하세요.',
    'inpaint.modeDeactivated': '참조선택 모드가 해제되었습니다.',
    'inpaint.exitMode': '참조선택 모드 해제',
    'inpaint.enterMode': '참조선택 모드',
    'inpaint.undoRedo': '실행 취소/다시 실행',
    'inpaint.drawingTools': '그리기 도구',
    'inpaint.clearAll': '전체 삭제',
    // Generation options bar
    'genOptions.fullOutfit': '전체 의상',
    'genOptions.top': '상의',
    'genOptions.bottom': '하의',
    'genOptions.partsCount': '수정부위 {count}개',
    'genOptions.concept': '컨셉',
    'genOptions.conceptLabel': '컨셉: {label}',
    'genOptions.camera': '카메라 옵션',
    'genOptions.pose': '포즈 옵션',
    'genOptions.paletteLabel': '팔레트: {name}',
    'genOptions.resolution': '해상도: {value}',
    'genOptions.ratio': '비율: {value}',
    // Memory management
    'settings.developerModeTitle': '개발자 모드',
    'settings.developerModeDescription': '메모리 패널에서 고급 텍스처 통계(bindCount, 누수 후보)를 표시합니다.',
    'settings.memoryTitle': '메모리 관리',
    'settings.memoryDescription': '이미지가 많아지면 메모리 사용량이 증가합니다. 주기적으로 정리해주세요.',
    // Glass effect
    'settings.glassEffectTitle': '리퀴드 글라스 효과',
    'settings.glassEffectDescription': '줌/패닝 시 깜빡임이 발생하면 끄세요.',
    'settings.groupAutoAddTitle': '그룹 이미지 자동 추가',
    'settings.groupAutoAddDescription': '이미지를 그룹 위로 옮기면 자동으로 그룹에 추가합니다.',
    'settings.autoAddToCanvasTitle': '생성이미지 자동추가',
    'settings.autoAddToCanvasDescription': '생성된 이미지를 무한 캔버스에 자동으로 배치합니다. 끄면 생성기록에만 표시됩니다.',
    'settings.undoHistoryTitle': '실행 취소 기록 수',
    'settings.undoHistoryDescription': '되돌릴 수 있는 작업 수를 설정합니다.',
    'settings.autoResumeOnRateLimitTitle': '할당량 초과 시 자동 재개',
    'settings.autoResumeOnRateLimitDescription': '429 에러 발생 후 60초 뒤 자동으로 생성을 재시도합니다.',
    'settings.autoClosePopoverOnGenerateTitle': '생성 시 패널 자동 닫기',
    'settings.autoClosePopoverOnGenerateDescription': '생성 버튼 클릭 시 도구 패널을 자동으로 닫습니다.',
    'settings.autoOpenEditorOnOriginalTitle': '원본 이미지 지정 시 에디터 자동 호출',
    'settings.autoOpenEditorOnOriginalDescription': '원본 역할 이미지 지정 시 편집 툴 팝오버를 자동으로 엽니다. 툴바가 패널에 도킹된 경우 비활성화됩니다.',
    'settings.autoBindToolbarToOriginalTitle': '원본 이미지 선택 시 툴바 자동 연결',
    'settings.autoBindToolbarToOriginalDescription': '원본 이미지 선택 시 툴바를 이미지 선택바에 자동으로 연결하고 가로 모드로 전환합니다.',
    'settings.flickPanningTitle': '플릭 패닝',
    'settings.flickPanningDescription': '캔버스 패닝 시 관성을 적용하여 미끄러지듯 이동합니다.',
    'settings.autoGroupGeneratedTitle': '생성이미지 자동 그룹화',
    'settings.autoGroupGeneratedDescription': '이미지를 생성할 때 원본과 결과 이미지들을 하나의 그룹으로 자동으로 묶습니다.',
    // Settings section headers
    'settings.section.display': '화면',
    'settings.section.workspace': '워크스페이스',
    'settings.section.system': '시스템',
    'settings.section.canvas': '캔버스',
    'settings.section.toolbar': '툴바',
    'settings.section.generation': '생성',
    // Toolbar orientation setting
    // UI Font scale setting (슬라이더 70%~150%)
    // Credit label
    'settings.creditLabel': '크레딧',
    // Pricing popover
    'settings.pricing.title': '해상도별 이미지 생성 가격 (Gemini 3.1 Flash Image Preview)',
    'settings.pricing.subtitle': 'Gemini 3.1 Flash Image Preview 기준 실제 이미지 생성 비용 ($ USD)',
    'settings.pricing.basicTitle': '1K 해상도 (~1MP)',
    'settings.pricing.recommended': '가장 표준적인 규격',
    'settings.pricing.modelName': '모델명:',
    'settings.pricing.perImage': '/ 이미지 1장',
    'settings.pricing.basicBenefit': '가장 표준적인 규격: 빠른 속도와 합리적인 비용으로 일반적인 이미지 생성에 최적화되어 있습니다.',
    'settings.pricing.proTitle': '2K / 4K 해상도',
    'settings.pricing.standardRes': '2K (~4MP)',
    'settings.pricing.fourKRes': '4K (~16MP)',
    'settings.pricing.proBenefit': '고해상도: 2K는 장당 약 $0.101, 4K는 장당 약 $0.151입니다.',
    'settings.pricing.usageExamples': '가격 사용 예시',
    'settings.pricing.basicExample': '1K 100장 ≈ $6.70',
    'settings.pricing.proExample': '2K 100장 ≈ $10.10',
    'settings.pricing.pro4kExample': '4K 100장 ≈ $15.10',
    'settings.pricing.1kDefault': '1K (기본)',
    'settings.pricing.flashExample': '100장 × $0.039 = $3.90',
    'settings.pricing.flashBulkExample': '500장 × $0.039 = $19.50',
    'settings.pricing.disclaimer': '가격은 Google의 공식 정책에 따라 변경될 수 있습니다.',
    'settings.pricing.officialLink': 'Google AI 공식 사이트',
    'settings.pricing.allResFlat': '모든 해상도 동일',
    'settings.pricing.variesByRes': '해상도별 상이',
    'settings.pricing.fastestBadge': '가장 빠름',
    // Account settings - Vertex AI
    'appSettingsModal.vertexConnected': '연결됨',
    'appSettingsModal.gcloudAuthActive': 'gcloud 인증 활성화됨',
    'appSettingsModal.accountLabel': '계정:',
    'appSettingsModal.usingADC': '기본 자격 증명(ADC) 사용 중',
    'appSettingsModal.switchingAccount': '전환 중...',
    'appSettingsModal.switchAccount': '계정 전환',
    'appSettingsModal.disconnect': '연결 해제',
    'appSettingsModal.checkingLogin': '로그인 상태 확인 중...',
    'appSettingsModal.connectDescription': 'Google Cloud 계정에 연결하여 Vertex AI 모델을 사용하세요.',
    'appSettingsModal.connecting': '연결 중...',
    'appSettingsModal.connectGcloud': 'gcloud로 연결',
    'appSettingsModal.cliCheckTitle': 'CLI 연결 확인',
    'appSettingsModal.cliCheckDescription': 'CLI 연결 설정이 완료되어야 계정 연결이 정상적으로 작동합니다.',
    'appSettingsModal.cliGuideLink': '설치 방법 안내',
    'appSettingsModal.select': '선택',
    'appSettingsModal.selected': '선택됨',
    'appSettingsModal.vertexDescription': 'Google Cloud gcloud 인증',
    'appSettingsModal.gasDescription': 'API 키 인증',
    // Shortcut actions
    'shortcut.toggleGroup': '그룹화/그룹 해제',
    'shortcut.mergeGroups': '그룹 병합',
    'shortcut.openEditor': '이미지 에디터 열기',
    'shortcut.generateImage': '이미지 생성',
    'shortcut.panCanvas': '캔버스 이동 (패닝)',
    'shortcut.translateMemo': '메모 번역 (스페이스바 3회)',
    'shortcut.cancel': '취소/닫기',
    // Shortcut confirm/cancel
    'appSettingsModal.confirm': '확인',
    'appSettingsModal.cancelShortcut': '취소',
    // Sidebar
    'appSettingsModal.resetApp': '앱 초기화',
    // Memory Monitor
    'memoryMonitor.title': '메모리 모니터',
    'memoryMonitor.refresh': '리프레시',
    'memoryMonitor.refreshTooltip': 'File 디스크 오프로딩 (메모리 대량 해제)',
    'memoryMonitor.cleanupTooltip': '메모리 정리 (File 디스크 오프로딩)',
    'memoryMonitor.estimatedMemory': '메모리 (추정)',
    'memoryMonitor.canvasImages': '캔버스 이미지',
    'memoryMonitor.recommended': '권장',
    'memoryMonitor.lastCleanup': '마지막 정리',
    'memoryMonitor.secondsAgo': '{seconds}초 전',
    'memoryMonitor.noCleanup': '-',
    'memoryMonitor.cleanupSuccess': '{count}장 이미지 메모리 해제',
    'memoryMonitor.cleanupComplete': '메모리 정리 완료',
    'memoryMonitor.blobsCleaned': '{count} blob 정리',
    'memoryMonitor.cleanupFailed': '정리 실패',
    'memoryMonitor.highMemoryWarning': '메모리 사용량이 높습니다. 정리를 권장합니다.',
    'memoryMonitor.memoryTrend': '메모리 사용량 추이',
    'memoryMonitor.gpuError': 'GPU 모니터링 오류: {error}',
    'memoryMonitor.dedicated': '전용: ',
    'memoryMonitor.shared': '공유: ',
    'memoryMonitor.5min': '5분',
    'memoryMonitor.1hr': '1시간',
    'memoryMonitor.gpuVram': 'GPU VRAM',
    'memoryMonitor.appMemory': '앱 메모리',
    'memoryMonitor.cleanupEvent': '정리',
    'memoryMonitor.collectingData': '데이터 수집 중...',
    // CLI Guide Modal
    'cliGuide.title': 'CLI 설치 및 인증 가이드',
    'cliGuide.section1.title': 'Google Cloud CLI 설치 및 인증 (열쇠 대신 지문 등록)',
    'cliGuide.section1.description': "'Google Cloud CLI 설치 및 인증' 부분과 '프로젝트 정보 입력(연결)' 과정을 아주 상세하게, 매뉴얼처럼 정리해 드리겠습니다.",
    'cliGuide.section1.linkText': 'https://cloud.google.com/sdk/docs/install?hl=ko',
    'cliGuide.section1.warning': 'API 키를 사용할 수 없는 환경에서는 <strong>"내 컴퓨터 자체를 인증된 기기로 만드는 과정"</strong>이 필수입니다.',
    'cliGuide.section1.step1.title': '① 설치 및 초기화',
    'cliGuide.section1.step1.item1': 'Google Cloud CLI 프로그램을 다운로드하여 설치합니다.',
    'cliGuide.section1.step1.item2': '설치가 끝나면 터미널(CMD 또는 PowerShell)이 열리는데, 여기서 당황하지 않고 명령어를 입력해야 합니다.',
    'cliGuide.section1.step2.title': '② 로그인 명령어 입력 (가장 중요!)',
    'cliGuide.section1.step2.description': '터미널에 아래 명령어를 입력합니다.',
    'cliGuide.section1.step3.title': '③ "Y/n" 질문에 대답하기',
    'cliGuide.section1.step3.description': '명령어를 치면 컴퓨터가 "계속하려면 로그인이 필요합니다. 로그인하시겠습니까?"라고 영어로 물어봅니다.',
    'cliGuide.section1.step3.item1': '여기서 <span class="text-yellow-400 font-bold">Y</span> (대문자/소문자 상관없음)를 입력하고 Enter를 누릅니다.',
    'cliGuide.section1.step3.item2': '이 부분이 막히셨던 포인트인데, <span class="text-yellow-400 font-bold">Y</span>를 눌러야 브라우저 창이 열립니다.',
    'cliGuide.section1.step4.title': '④ 구글 로그인 및 허용',
    'cliGuide.section1.step4.item1': '웹 브라우저가 자동으로 뜨면 회사 구글 계정(...ncsoft.com)을 선택합니다.',
    'cliGuide.section1.step4.item2': '"Google Cloud SDK에 권한을 허용하시겠습니까?" 창에서 <strong>[허용]</strong>을 클릭합니다.',
    'cliGuide.section1.step4.item3': '브라우저에 "이제 인증되었습니다"라는 문구가 뜨면 성공입니다.',
    'cliGuide.section2.title': '프로젝트 정보 입력 (목적지 설정)',
    'cliGuide.section2.description': '인증은 되었지만, 컴퓨터는 "어떤 프로젝트"에서 작업을 수행할지 모르는 상태입니다. 이 <strong>\'방향\'을 잡아주는 과정</strong>입니다.',
    'cliGuide.section2.step1.title': '① 프로젝트 선택 목록의 이해',
    'cliGuide.section2.step1.description': '로그인 직후 터미널에 아래와 같은 목록이 떴었습니다.',
    'cliGuide.section2.step1.item1': '이것은 "네 계정을 보니 사용 가능한 프로젝트가 이것들이 있네? 어떤 거 쓸래?"라고 묻는 것입니다.',
    'cliGuide.section2.step1.item2': '사용자님의 경우 <strong>[1]</strong>번에 회사 프로젝트가 정확히 떴으므로, 숫자 <strong>1</strong>을 입력하고 Enter를 치면 가장 쉽게 설정이 끝납니다.',
    'cliGuide.section2.step2.title': '② (대안) 명령어로 강제 고정하기',
    'cliGuide.section2.step2.description': '만약 목록에서 실수를 했거나, 나중에 프로젝트를 바꾸고 싶다면 아래 명령어를 기억해 주세요. 이것은 "다 무시하고 이 프로젝트를 바라봐!"라고 강제로 설정하는 명령어입니다.',
    'cliGuide.section2.step2.note': '(뒤에 nc-gdevelop-projectngu 는 당신의 고유한 프로젝트 ID입니다.)',
    'cliGuide.section3.title': 'BanaNyang 앱 연결 및 로그인',
    'cliGuide.section3.description': '모든 CLI 설정이 완료되었습니다! 이제 바나냥 앱에서 연결을 마무리해 주세요.',
    'cliGuide.section3.step1.title': '① 이 창 닫기',
    'cliGuide.section3.step1.description': '우측 상단의 닫기 버튼(X)을 눌러 이 가이드를 닫습니다.',
    'cliGuide.section3.step2.title': '② "Connect with gcloud" 버튼 클릭',
    'cliGuide.section3.step2.description': '설정 화면에 있는 <strong>"Connect with gcloud"</strong> 버튼을 클릭합니다.',
    'cliGuide.section3.step3.title': '③ 연결 확인',
    'cliGuide.section3.step3.description': '잠시 후 <span class="text-green-500 font-bold">Connected</span> 상태로 변경되면 모든 준비가 끝났습니다.<br />이제 Vertex AI 모델을 자유롭게 사용하실 수 있습니다!',
    'cliGuide.section3.congrats': '🎉 축하합니다!',
    'cliGuide.section3.congratsDescription': '이제 BanaNyang의 모든 AI 기능을 안전하게 사용하실 수 있습니다.',
    // AuthGate
    'auth.modal.canvasFree': '무한 캔버스는 로그인 없이 바로 사용할 수 있습니다.',
    'auth.modal.aiRequiresLogin': 'AI 이미지 생성 기능을 사용하려면 Google 계정으로 로그인이 필요합니다.',
    'auth.modal.apiKeyNote': 'AI 생성에는 개인 Google API 키 또는 Vertex AI 계정이 별도로 필요합니다.',
    'auth.modal.loggingIn': '로그인 중...',
    'auth.modal.loginNow': 'Google 계정으로 로그인',
    'auth.modal.skip': '건너뛰기 (캔버스만 사용)',
    'auth.notPurchased.title': '구매가 필요합니다',
    'auth.notPurchased.account': '로그인 계정:',
    'auth.notPurchased.body': '이 계정에 활성화된 구매 내역이 없습니다.',
    'auth.notPurchased.button': '구매 페이지로 이동',
    'auth.notPurchased.switchAccount': '다른 계정으로 로그인',
    'auth.graceExpired.title': '오프라인 기간 만료',
    'auth.graceExpired.body': '마지막 온라인 인증 후 {days}일이 경과했습니다. 인터넷에 연결한 후 다시 시도해주세요.',
    'auth.graceExpired.button': '다시 인증하기',
    'auth.offline.banner': '⚠️ 오프라인 모드 — 남은 Grace Period: {days}일',
    // Login form
    'auth.login.emailPlaceholder': '이메일',
    'auth.login.passwordPlaceholder': '비밀번호',
    'auth.login.button': '로그인',
    'auth.login.or': '또는',
    // BanaNyang Account
    'account.sectionTitle': 'BanaNyang 계정',
    'account.login': '로그인',
    'account.logout': '로그아웃',
    'account.autoLogin': '자동 로그인',
    'account.autoLoginDescription': '앱 시작 시 자동으로 로그인',
    'account.notLoggedIn': '로그인되지 않음',
    // Canvas safety warnings
    'canvas.zoomStress.warning': '과도한 줌 조작은 앱 불안정을 유발할 수 있습니다. 속도를 늦춰 주세요.',
    'canvas.renderError.title': '렌더링 오류',
    'canvas.renderError.message': 'UI 렌더링 오류가 발생했습니다. 앱을 재시작하세요.',
    // Prompt textarea context menu
    'contextMenu.prompt.edit': '편집',
    'contextMenu.prompt.cut': '잘라내기',
    'contextMenu.prompt.copy': '복사',
    'contextMenu.prompt.copyAll': '전체 복사',
    'contextMenu.prompt.paste': '붙여넣기',
    'contextMenu.prompt.pasteReplace': '붙여넣기 및 교체',
    'contextMenu.prompt.selectAll': '전체 선택',
    'contextMenu.prompt.delete': '삭제',
    'contextMenu.prompt.clearPrompt': '프롬프트 지우기',
    // Pricing tab navigation
    'settings.pricing.tab.gemini': 'Gemini',
    'settings.pricing.tab.openai': 'OpenAI',
    'settings.pricing.tab.flux': 'Flux',
    // OpenAI gpt-image-2 pricing
    'settings.pricing.openai.title': 'OpenAI gpt-image-2',
    'settings.pricing.openai.lowLabel': '저품질 (1024²)',
    'settings.pricing.openai.medLabel': '표준 (1024²)',
    'settings.pricing.openai.highLabel': '고품질 (1024²)',
    'settings.pricing.openai.note': '토큰 기반 가격, 1024×1024 기준. 편집 시 입력 이미지 추가 토큰 청구.',
    'settings.pricing.openai.officialLink': 'OpenAI 공식 문서',
    'settings.pricing.openai.standardBadge': '표준',
    // Flux 2 Max pricing
    'settings.pricing.flux.title': 'Flux 2 Max',
    'settings.pricing.flux.note': '메가픽셀 기반 가격 ($0.07/MP). 워터마크 없음, 상업적 사용 가능.',
    'settings.pricing.flux.officialLink': 'BFL 공식 가격 페이지',
    'settings.pricing.flux.defaultBadge': '기본',
    'settings.pricing.flux.recommendedBadge': 'Max 권장',
    // Flux quality hint
    'flux.qualityHint': '최고 품질을 원하면 2MP 이상 권장',
    // OpenAI Quality
    'quality': '품질',
    'quality.auto': '자동',
    'quality.high': '고품질',
    'quality.medium': '중간',
    'quality.low': '낮음',
    // Workspace save/load loading messages
    'workspace.save.sourcelessWarning': '{count}개의 이미지가 소스를 찾을 수 없습니다. 저장을 계속하면 해당 이미지는 포함되지 않습니다.\n\n계속 저장하시겠습니까?',
    'workspace.save.saving': '워크스페이스 저장 중: {title}',
    'workspace.save.processingImages': '{title} — 이미지 처리 중... ({current}/{total})',
    'workspace.save.generatingThumbnails': '{title} — 썸네일 생성 중...',
    'workspace.save.writingFile': '{title} — 파일 저장 중...',
    'workspace.load.loading': '워크스페이스 불러오는 중...',
    'workspace.load.processing': '워크스페이스 처리 중... ({current}/{total})',
    'workspace.load.optimizing': '워크스페이스 최적화 중... ({current}/{total})',
    'workspace.load.convertingHighRes': '고해상도 변환 중... ({current}/{total})',
    // Notification messages
    'notification.highMemory': '메모리 사용량이 높습니다. 워크스페이스를 저장하고 앱을 재시작하는 것을 권장합니다.',
    'notification.imageStillLoading': '이미지가 아직 로딩 중입니다. 잠시 후 다시 시도해주세요.',
    'notification.tabLockedDuringLoad': '안정적인 이미지 로드를 위해 로딩이 완료된 이후 조작해 주세요.',
    'notification.imageSourceUnavailable': '이미지 소스를 불러올 수 없습니다.',
    'notification.imageLoadError': '이미지를 불러오는 중 오류가 발생했습니다.',
    'notification.addLightFirst': '조명을 하나 이상 추가해주세요.',
    'notification.originalImageLoadFailed': '원본 이미지를 불러오는데 실패했습니다.',
    'notification.originalImageFileMissing': '원본 이미지 파일이 없습니다.',
    'notification.clipboard.copyLimitExceeded': '최대 {count}장까지만 복사할 수 있습니다. 선택을 줄여주세요.',
    'notification.clipboard.copying': '이미지 복사중',
    'notification.clipboard.pasting': '이미지 붙여넣기중',
    'notification.clipboard.loadError': '이미지 데이터를 불러올 수 없습니다. 줌 레벨을 40% 이상으로 올린 후 다시 시도해주세요.',
    'notification.imageLimit.hardExceeded': '🚫 이미지 한도 초과 · {count} / {hardLimit}장 · 이미지를 삭제해주세요',
    'notification.imageLimit.hardReached': '🚫 이미지 한도 도달 · {count} / {hardLimit}장 · 더 이상 추가할 수 없습니다',
    'notification.imageLimit.strong': '⚠️ 이미지 제한 임박 · {count} / {hardLimit}장 ({pct}%) · 일부 이미지를 정리하세요',
    'notification.imageLimit.warn': '💡 이미지 권장 초과 · {count} / {hardLimit}장 ({pct}%) · 불필요한 이미지를 정리해주세요',
    'canvas.downloadToFolder': '{count}개의 파일이 {folder} 폴더에 저장되었습니다.',
    // Toolbar tooltips
    'toolbar.title': '도구 모음',
    'toolbar.undock': '도킹 해제',
    'toolbar.goToImage': '이미지로 이동',
    'toolbar.unbindImage': '편집 버튼 연결 해제',
    'toolbar.dockToToolbar': '툴바에 도킹',
    'toolbar.minimize': '최소화',
    'toolbar.restore': '복원',
    'toolbar.close': '닫기',
    'toolbar.thinkingLevel': '사고 수준 (클릭으로 순환)',
    'toolbar.thinkingLabel.off': '사고',
    'toolbar.thinkingLabel.minimal': '사고·Min',
    'toolbar.thinkingLabel.high': '사고·High',
    // Tab / Panel tooltips
    'tab.newTab': '새 탭 (Ctrl+T)',
    'tab.unsavedChanges': '저장되지 않은 변경사항',
    'tab.close': '탭 닫기',
    'tab.closeOthers': '다른 탭 모두 닫기',
    'tab.closeRight': '오른쪽 탭 모두 닫기',
    'tab.openFileLocation': '파일 위치 열기',
    'panel.unsnapGroup': '스냅 그룹 해제',
    'panel.undockSidebar': '사이드바 도킹 해제',
    'panel.bindToolbar': '툴바를 이 패널에 고정',
    // Tooltip misc
    'tooltip.aPoseDescription': 'A-Pose: 전신 정면 포즈',
    // Exit confirm modal (tab close variant)
    'exitConfirmModal.bodyCloseTab': '\'{title}\' 탭에 저장되지 않은 변경사항이 있습니다. 탭을 닫으시겠습니까?',
    'exitConfirmModal.bodyCloseMultipleTabs': '{count}개 탭에 저장되지 않은 변경사항이 있습니다. 모두 저장하시겠습니까?',
    // Login prompt
    'loginPrompt.title': '이미지 생성 로그인 필요',
    'loginPrompt.body': 'AI 이미지 생성을 사용하려면\n로그인 또는 API 설정이 필요합니다.',
    'loginPrompt.apiKeyNote': '개인 Google API 키 또는 Vertex AI 계정이 필요합니다',
    'loginPrompt.goToSettings': '설정에서 연결하기',
    'loginPrompt.skip': '건너뛰기 — 나중에 설정하기',
    // Flux API settings
    'settings.flux.apiKeySaved': 'Flux API 키가 저장되었습니다.',
    'settings.flux.apiKeyDeleted': 'Flux API 키가 삭제되었습니다.',
    'settings.flux.enterApiKeyFirst': 'API 키를 먼저 입력해 주세요.',
    'settings.flux.apiKeyValid': 'Flux API 키가 유효합니다.',
    'settings.flux.apiKeyInvalid': '유효하지 않은 Flux API 키입니다. (401/403)',
    'settings.flux.validationError': '키 검증 중 오류가 발생했습니다.',
    'settings.flux.invalidOrgIdFormat': '조직 ID 형식이 올바르지 않습니다. (UUID 형식이어야 합니다)',
    'settings.flux.orgIdSaved': '조직 ID가 저장되었습니다.',
    'settings.flux.orgIdDeleted': '조직 ID가 삭제되었습니다.',
    'settings.flux.apiKeyLabel': 'API 키 (x-key)',
    'settings.flux.showKey': '표시',
    'settings.flux.hideKey': '숨기기',
    'settings.flux.creditsLabel': '보유 크레딧',
    'settings.flux.registerApiKeyFirst': 'API 키를 먼저 등록하세요',
    'settings.flux.loadingCredits': '조회 중...',
    'settings.flux.loadFailed': '조회 실패',
    'settings.flux.refreshCredits': '새로고침',
    'settings.flux.rechargeCredits': '크레딧 충전',
    'settings.flux.enterOrgIdFirst': '조직 ID를 먼저 입력하세요',
    'settings.flux.openRechargePage': '크레딧 충전 페이지 열기',
    'settings.flux.orgIdLabel': 'BFL 조직 ID',
    'settings.flux.save': '저장',
    'settings.flux.orgIdDescription': '크레딧 충전 페이지를 열려면 BFL 대시보드에서 조직 ID를 복사해 입력하세요.',
    'settings.flux.delete': '삭제',
    'settings.flux.validating': '검증 중…',
    'settings.flux.validateKey': '키 검증',
    'settings.flux.apiKeyDescription': 'API 키는 BFL 계정 대시보드에서 발급받을 수 있습니다. 상세 사용량 내역은 dashboard.bfl.ai에서 확인하세요.',
    'settings.flux.apiKeyPageLink': 'BFL API 키 발급 페이지 열기 →',
    'settings.flux.creditInfo': '1 credit = $0.01 · 60초마다 자동 갱신',
    // Google AI settings
    'settings.google.apiKeyChanged': 'API 키가 변경되었습니다.',
    'settings.google.apiKeyDeleted': 'API 키가 삭제되었습니다.',
    'settings.google.noActiveKey': '활성 API 키가 없습니다.',
    'settings.google.apiKeyValid': 'API 키가 유효합니다.',
    'settings.google.apiKeyInvalid': '유효하지 않은 API 키입니다.',
    'settings.google.validationError': '키 검증 중 오류가 발생했습니다.',
    'settings.google.enterApiKeyFirst': 'API 키를 입력해 주세요.',
    'settings.google.apiKeyAdded': 'API 키가 추가되었습니다.',
    'settings.google.apiKeyLabel': 'API 키',
    'settings.google.selectOrAddKey': '키를 선택하거나 추가해 주세요',
    'settings.google.noKeysRegistered': '등록된 API 키가 없습니다',
    'settings.google.showKey': '표시',
    'settings.google.hideKey': '숨기기',
    'settings.google.editLabel': '라벨 수정',
    'settings.google.deleteKey': '삭제',
    'settings.google.cancel': '취소',
    'settings.google.add': '추가',
    'settings.google.addKey': '키 추가',
    'settings.google.validating': '검증 중…',
    'settings.google.validateKey': '키 검증',
    'settings.google.apiKeyDescription': 'API 키는 Google AI Studio에서 발급받을 수 있습니다. 사용량 및 요금은 aistudio.google.com에서 확인하세요.',
    'settings.google.apiKeyPageLink': 'Google AI Studio API 키 발급 페이지 열기 →',
    'settings.google.spendPageLink': 'Google AI 지출 현황 보기 →',
    'settings.google.spendLimitLink': '월 사용 한도 설정 →',
    // OpenAI settings
    'settings.openai.saved': 'OpenAI 설정이 저장되었습니다.',
    'settings.openai.deleted': 'OpenAI 설정이 삭제되었습니다.',
    'settings.openai.enterApiKeyFirst': 'API 키를 먼저 입력해 주세요.',
    'settings.openai.apiKeyValid': 'OpenAI API 키가 유효합니다.',
    'settings.openai.apiKeyInvalid': '유효하지 않은 OpenAI API 키입니다.',
    'settings.openai.validationError': '키 검증 중 오류가 발생했습니다.',
    'settings.openai.apiKeyLabel': 'API 키',
    'settings.openai.showKey': '표시',
    'settings.openai.hideKey': '숨기기',
    'settings.openai.delete': '삭제',
    'settings.openai.validating': '검증 중…',
    'settings.openai.validateKey': '키 검증',
    'settings.openai.save': '저장',
    'settings.openai.apiKeyDescription': 'API 키는 OpenAI 플랫폼에서 발급받을 수 있습니다. 바나냥 같은 외부 앱에서 gpt-image-2 모델을 사용하려면 OpenAI 조직 인증(Verify Organization)이 필요합니다.',
    'settings.openai.apiKeyPageLink': 'OpenAI API 키 발급 페이지 열기 →',
    'settings.openai.verificationPageLink': 'OpenAI 조직 인증 페이지 열기 →',
    'settings.openai.rechargeCredits': '크레딧 충전',
    'settings.openai.openRechargePage': 'OpenAI 결제 페이지 열기',
    // AppSettingsModal — Vertex AI / Google Auth section
    'appSettingsModal.projectListFailed': '프로젝트 목록을 가져올 수 없습니다. 수동으로 입력해 주세요.',
    'appSettingsModal.authCancelled': '인증이 취소되었습니다. 다시 시도하려면 버튼을 눌러 주세요.',
    'appSettingsModal.authUnavailable': 'Google 인증을 사용할 수 없습니다. 앱을 재시작해 주세요.',
    'appSettingsModal.connectionFailed': '연결에 실패했습니다.',
    'appSettingsModal.unknownError': '알 수 없는 오류가 발생했습니다.',
    'appSettingsModal.switchAccountFailed': '계정 전환에 실패했습니다.',
    'appSettingsModal.disconnected': '연결이 해제되었습니다.',
    'appSettingsModal.vertexActivationLabel': 'Vertex AI 활성화',
    'appSettingsModal.vertexActivationTooltip': 'Vertex AI와 Google AI Studio는 같은 Gemini 모델을 공유합니다. 동시에 하나만 활성화할 수 있으며, 한쪽을 켜면 다른 쪽이 자동으로 꺼집니다.',
    'appSettingsModal.vertexCallingAccount': '이 계정으로 Gemini 모델을 호출합니다',
    'appSettingsModal.checkingConnection': '연결 상태 확인 중…',
    'appSettingsModal.vertexConnectedLabel': 'Vertex AI 연결됨',
    'appSettingsModal.projectIdUpdated': '프로젝트 ID가 업데이트되었습니다.',
    'appSettingsModal.saveProjectId': '저장',
    'appSettingsModal.changeProject': '프로젝트 변경',
    'appSettingsModal.processing': '처리 중…',
    'appSettingsModal.accountConnected': '계정 연결됨 — 프로젝트를 선택하세요',
    'appSettingsModal.selectProject': '아래 목록에서 프로젝트를 클릭하여 선택해 주세요',
    'appSettingsModal.loadingProjects': '프로젝트 목록을 가져오는 중…',
    'appSettingsModal.clickProjectBelow': '아래 목록에서 프로젝트를 클릭하여 선택해 주세요',
    'appSettingsModal.searchProject': '프로젝트 검색…',
    'appSettingsModal.projectNotFound': '프로젝트를 찾을 수 없습니다. 직접 입력해 주세요.',
    'appSettingsModal.browserAuthInProgress': '브라우저에서 인증 중…',
    'appSettingsModal.allowGoogleAuth': 'Google 계정을 선택하고 권한을 허용해 주세요.',
    'appSettingsModal.connectGoogle': 'Google로 연결하기',
    'appSettingsModal.retry': '다시 시도',
    'appSettingsModal.clickToConnect': '버튼 클릭 시 브라우저가 열리고 Google 계정 선택 → 권한 허용 후 프로젝트를 선택할 수 있습니다.',
    'appSettingsModal.gasActivationLabel': 'Google AI Studio 활성화',
    'appSettingsModal.gasActivationTooltip': 'Vertex AI와 Google AI Studio는 같은 Gemini 모델을 공유합니다. 동시에 하나만 활성화할 수 있으며, 한쪽을 켜면 다른 쪽이 자동으로 꺼집니다.',
    'appSettingsModal.gasCallingAccount': '이 계정으로 Gemini 모델을 호출합니다',
    'appSettingsModal.resetThumbnailHandler': '썸네일 핸들러 재설정',
    'appSettingsModal.resetThumbnailHandlerDesc': 'Windows 탐색기의 .nyang 미리보기를 재등록합니다. 우측 하단 추가 아이콘이 보이거나 썸네일이 표시되지 않을 때 사용.',
    'appSettingsModal.thumbnailReregisterComplete': '재등록 완료.',
    'appSettingsModal.thumbnailReregisterFailed': '실패: {reason}',
    'appSettingsModal.thumbnailError': '오류 발생.',
    'appSettingsModal.resetThumbnailButton': '재설정',
    // Flux provider errors
    'error.flux.apiKeyMissing': 'Flux API 키가 설정되지 않았습니다.',
    'error.flux.apiKeyInvalid': 'Flux API 키가 유효하지 않습니다.',
    'error.flux.creditQueryFailed': 'Flux 크레딧 조회 실패 ({status})',
    'error.flux.downloadFailed': 'Flux 결과 이미지 다운로드에 실패했습니다.',
    'error.flux.pollingError': 'Flux 폴링 오류 ({status})',
    'error.flux.noImageUrl': 'Flux에서 이미지 URL을 받지 못했습니다.',
    'error.flux.generationFailed': 'Flux 생성 실패: {status}',
    'error.flux.timeout': 'Flux 생성 시간이 초과되었습니다 (180초).',
    'error.flux.apiKeyMissingFull': 'Flux API 키가 설정되지 않았습니다. 설정 → API → Flux에서 키를 입력해 주세요.',
    'error.flux.creditInsufficient': 'Flux 크레딧이 부족합니다. BFL 대시보드에서 크레딧을 충전해 주세요.',
    'error.flux.rateLimited': 'Flux 요청 한도를 초과했습니다. 잠시 후 다시 시도해 주세요.',
    'error.flux.genericError': 'Flux 오류 ({status}): {error}',
    'error.flux.noJobId': 'Flux에서 작업 ID를 받지 못했습니다.',
    'error.flux.retryFailed': 'Flux 생성에 반복 실패했습니다. 잠시 후 다시 시도해 주세요.',
    'error.flux.moderated': '콘텐츠 안전 정책에 의해 요청이 거절되었습니다. 프롬프트나 입력 이미지를 조정해 다시 시도해 주세요.',
    'error.flux.taskNotFound': 'Flux 작업을 찾을 수 없습니다. 재시도 중...',
    // OpenAI provider errors
    'error.openai.apiKeyInvalid': 'OpenAI API 키가 유효하지 않습니다.',
    'error.openai.rateLimited': 'OpenAI 사용량 한도를 초과했습니다. 잠시 후 다시 시도해 주세요.',
    'error.openai.orgVerification': 'OpenAI 조직 인증이 필요합니다.\nhttps://platform.openai.com/settings/organization/general 에서 "Verify Organization" 버튼을 눌러 인증을 완료해 주세요.\n(인증 후 권한 반영까지 최대 15분 소요)',
    'error.openai.genericError': 'OpenAI 오류 ({status}): {error}',
    'error.openai.noImage': 'OpenAI에서 이미지를 생성하지 못했습니다.',
    'error.openai.noEditImage': 'OpenAI에서 편집된 이미지를 가져오지 못했습니다.',
    'error.openai.apiKeyMissing': 'OpenAI API 키가 설정되지 않았습니다. 설정 → API → OpenAI에서 키를 입력해 주세요.',
    'error.openai.editGenericError': 'OpenAI 편집 오류 ({status}): {error}',
    // OTA Auto-Update
    'settings.autoUpdate.label': '자동 업데이트',
    'settings.autoUpdate.description': 'ON: 새 버전을 백그라운드에서 받아 다음 종료 시 자동 적용 / OFF: 매번 알림으로 확인',
    'update.toast.available': '새 버전 사용 가능',
    'update.toast.downloading': '다운로드 중...',
    'update.toast.ready': '업데이트 준비 완료',
    'update.toast.error': '업데이트 오류',
    'update.toast.later': '나중에',
    'update.toast.installNow': '지금 설치',
    'update.toast.installOnQuit': '다음 종료 시 적용',
    'update.toast.restartNow': '지금 재시작',
    'update.critical.title': '필수 업데이트',
    'update.critical.body': '보안 문제로 즉시 업데이트가 필요합니다. 작업을 저장한 뒤 재시작하세요.',
    'update.critical.restart': '지금 재시작하여 적용',
    'update.header.tooltip.idle': '업데이트 확인',
    'update.header.tooltip.checking': '업데이트 확인 중...',
    'update.header.tooltip.available': '업데이트 가능: v{version}',
    'update.header.tooltip.downloading': '다운로드 중... {percent}%',
    'update.header.tooltip.downloaded': 'v{version} 재시작하여 업데이트 적용',
    'update.header.tooltip.error': '업데이트 오류',
    'update.header.popup.title': '앱 업데이트',
    'update.header.popup.upToDate': '최신 버전입니다.',
    'update.header.popup.checkNow': '지금 확인',
    'update.header.popup.retry': '다시 시도',
    'inpaint.unsupported_model.title': '현재 모델은 인페인팅을 지원하지 않습니다',
    'inpaint.unsupported_model.body': '선택한 모델은 마스크 기반 편집을 지원하지 않습니다. Gemini 또는 OpenAI 이미지 편집 모델로 변경해 주세요.',
    'inpaint.unsupported_model.change_action': '모델 변경',
    'inpaint.unsupported_model.button_tooltip': '이 모델은 인페인팅을 지원하지 않습니다. 다른 모델을 선택하세요.',
    'editor.inpaint.smartMode.title': '스마트 자동 모드',
    'editor.inpaint.smartMode.help': '마스크와 선택적 설명으로 AI가 의도(제거/교체/보정/확장)를 자동 판단합니다.',
    'editor.inpaint.smartMode.auto': '자동',
    'editor.inpaint.smartMode.manual': '수동',
    'editor.inpaint.smartMode.hintPlaceholder': '이 영역을 어떻게 처리할까요? (선택 사항)',
    'editor.inpaint.aiChip.tip': 'AI 자동 추천 적용 중',
    'editor.inpaint.customChip.tip': '사용자 지정 값 사용 중',
    'editor.inpaint.resetToAI': 'AI 추천값으로 복귀',
    'editor.inpaint.variationStrength': '베리에이션',
    'editor.inpaint.variationStrength.help': '낮음 = 참조 이미지 충실 재현 / 높음 = AI가 더 자유롭게 변형. 프롬프트가 비어있을 때 가장 큰 영향을 줍니다.',
    'editor.inpaint.sceneAnalyzer': 'Scene Analyzer',
    'editor.inpaint.sceneAnalyzer.help': '원본·마스크·참조를 AI가 분석해 의도·해부학·투시·조명·재질을 자동 추출하여 프롬프트에 반영합니다.',
    'editor.inpaint.anatomyConstraints': '해부학 인식',
    'editor.inpaint.anatomyConstraints.help': '마스킹된 위치(어깨/팔/얼굴 등)를 인지해 잘못된 신체부위 생성을 차단합니다.',
    'editor.inpaint.sceneAware': '씬 분석 (투시/조명)',
    'editor.inpaint.sceneAware.help': '주변 투시·조명·재질을 분석해 합성 결과를 원본과 자연스럽게 통합합니다.',
    'editor.inpaint.userHint': '의도 (선택)',
    'editor.inpaint.userHint.help': '이 영역을 어떻게 처리하고 싶은지 짧게 적어주세요. 비워두면 AI가 알아서 판단합니다.',
    'editor.inpaint.userHint.placeholder': '예: 빨간 코트로 / 비워도 동작',
};
